package client

import (
	"fmt"
	"strings"

	"github.com/nafsilabs/massa-go/client/sendoperation/callsc"
	"github.com/nafsilabs/massa-go/client/sendoperation/executesc"
	"github.com/nafsilabs/massa-go/wallet"
)

type OperationWithEventResponse struct {
	Event             string
	OperationResponse OperationResponse
}

// CallFunction calls a function of a smart contract on the blockchain. It returns the operation ID or an Error if any.
// If `async` is true, it returns directly the operation ID and does not wait for the event.
// Otherwise, it waits for the first event generated by the smart contract and returns it along with the operation ID.
func CallFunction(
	c *Client,
	targetAddress string,
	callerAddress string,
	function string,
	parameter []byte,
	fee uint64,
	maxGas uint64,
	coins uint64,
	expiryDelta uint64,
	async bool,
	account *wallet.Account,
	password string,
	description string,
) (*OperationWithEventResponse, error) {

	// Calibrate max_gas
	if maxGas == 0 {
		estimatedGasCost, err := EstimateGasCostCallSC(account, password, targetAddress, callerAddress, function, parameter, coins, fee, c)
		if err != nil {
			return nil, fmt.Errorf("estimating Call SC gas cost for function '%s' at '%s': %w", function, targetAddress, err)
		}

		maxGas = estimatedGasCost
	}

	// Create the operation
	callSC, err := callsc.New(targetAddress, function, parameter,
		maxGas,
		coins)
	if err != nil {
		return nil, fmt.Errorf("creating callSC with '%s' at '%s': %w", function, targetAddress, err)
	}

	operationResponse, err := Call(
		c,
		expiryDelta,
		fee,
		callSC,
		account,
		password,
		description,
	)
	if err != nil {
		return nil, fmt.Errorf("calling function '%s' at '%s' with '%+v': %w", function, targetAddress, parameter, err)
	}

	return CallFunctionSuccess(async, operationResponse, c)
}

func CallFunctionSuccess(
	async bool,
	operationResponse *OperationResponse,
	c *Client,
) (*OperationWithEventResponse, error) {
	if async {
		return &OperationWithEventResponse{
			Event:             "Function called successfully but did not wait for event",
			OperationResponse: *operationResponse,
		}, nil
	}

	events, err := ListenEvents(c, nil, nil, nil, &operationResponse.OperationID, nil, true)
	if err != nil {
		if strings.Contains(err.Error(), "Timeout") {
			return &OperationWithEventResponse{
				Event:             "Operation submitted successfully but no event generated. The operation may have been rejected",
				OperationResponse: *operationResponse,
			}, nil
		}

		return nil, fmt.Errorf("listening events for opId at %s : %w", operationResponse.OperationID, err)
	}

	return &OperationWithEventResponse{
		Event:             events[0].Data, // return first event; TO DO: return all events
		OperationResponse: *operationResponse,
	}, nil
}

func ExecuteSC(
	c *Client,
	nickname string,
	maxGas uint64,
	maxCoins uint64,
	fees uint64,
	expiry uint64,
	bytecode []byte,
	datastore []ContractDatastoreEntry,
	account *wallet.Account,
	password string,
	description string,
) (*OperationResponse, error) {
	serializedDatastore, err := SerializeDatastore(datastore)
	if err != nil {
		return nil, err
	}

	exeSCOperation := executesc.New(
		bytecode,
		maxGas,
		maxCoins,
		serializedDatastore,
	)

	operationResponse, err := Call(
		c,
		expiry,
		fees,
		exeSCOperation,
		account,
		password,
		description,
	)
	if err != nil {
		return nil, fmt.Errorf("calling executeSC: %w", err)
	}

	return operationResponse, nil
}
