// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: massa/model/v1/address.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Address category discriminant
type AddressCategory int32

const (
	// Unspecified address category
	AddressCategory_ADDRESS_CATEGORY_UNSPECIFIED AddressCategory = 0
	// User address
	AddressCategory_ADDRESS_CATEGORY_USER_ADDRESS AddressCategory = 1
	// Smart contract address
	AddressCategory_ADDRESS_CATEGORY_SC_ADDRESS AddressCategory = 2
)

// Enum value maps for AddressCategory.
var (
	AddressCategory_name = map[int32]string{
		0: "ADDRESS_CATEGORY_UNSPECIFIED",
		1: "ADDRESS_CATEGORY_USER_ADDRESS",
		2: "ADDRESS_CATEGORY_SC_ADDRESS",
	}
	AddressCategory_value = map[string]int32{
		"ADDRESS_CATEGORY_UNSPECIFIED":  0,
		"ADDRESS_CATEGORY_USER_ADDRESS": 1,
		"ADDRESS_CATEGORY_SC_ADDRESS":   2,
	}
)

func (x AddressCategory) Enum() *AddressCategory {
	p := new(AddressCategory)
	*p = x
	return p
}

func (x AddressCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_massa_model_v1_address_proto_enumTypes[0].Descriptor()
}

func (AddressCategory) Type() protoreflect.EnumType {
	return &file_massa_model_v1_address_proto_enumTypes[0]
}

func (x AddressCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressCategory.Descriptor instead.
func (AddressCategory) EnumDescriptor() ([]byte, []int) {
	return file_massa_model_v1_address_proto_rawDescGZIP(), []int{0}
}

// Massa NativeAddress
type NativeAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address category
	Category AddressCategory `protobuf:"varint,1,opt,name=category,proto3,enum=massa.model.v1.AddressCategory" json:"category,omitempty"`
	// Address version
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Address content
	Content       []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NativeAddress) Reset() {
	*x = NativeAddress{}
	mi := &file_massa_model_v1_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeAddress) ProtoMessage() {}

func (x *NativeAddress) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeAddress.ProtoReflect.Descriptor instead.
func (*NativeAddress) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_address_proto_rawDescGZIP(), []int{0}
}

func (x *NativeAddress) GetCategory() AddressCategory {
	if x != nil {
		return x.Category
	}
	return AddressCategory_ADDRESS_CATEGORY_UNSPECIFIED
}

func (x *NativeAddress) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *NativeAddress) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// Addresses holds addresses
type Addresses struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Addresses
	Addresses     []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Addresses) Reset() {
	*x = Addresses{}
	mi := &file_massa_model_v1_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Addresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addresses) ProtoMessage() {}

func (x *Addresses) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addresses.ProtoReflect.Descriptor instead.
func (*Addresses) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_address_proto_rawDescGZIP(), []int{1}
}

func (x *Addresses) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

var File_massa_model_v1_address_proto protoreflect.FileDescriptor

const file_massa_model_v1_address_proto_rawDesc = "" +
	"\n" +
	"\x1cmassa/model/v1/address.proto\x12\x0emassa.model.v1\"\x80\x01\n" +
	"\rNativeAddress\x12;\n" +
	"\bcategory\x18\x01 \x01(\x0e2\x1f.massa.model.v1.AddressCategoryR\bcategory\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\")\n" +
	"\tAddresses\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses*w\n" +
	"\x0fAddressCategory\x12 \n" +
	"\x1cADDRESS_CATEGORY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dADDRESS_CATEGORY_USER_ADDRESS\x10\x01\x12\x1f\n" +
	"\x1bADDRESS_CATEGORY_SC_ADDRESS\x10\x02B\xa8\x01\n" +
	"\x12com.massa.model.v1P\x01Z<github.com/nafsilabs/massa-go/client/proto/massa/model/v1;v1\xa2\x02\x06MMODEL\xaa\x02\x12Com.Massa.Model.v1\xba\x02\x06MMODEL\xca\x02\x12Com\\Massa\\Model\\V1\xea\x02\x15Com::Massa::Model::V1b\x06proto3"

var (
	file_massa_model_v1_address_proto_rawDescOnce sync.Once
	file_massa_model_v1_address_proto_rawDescData []byte
)

func file_massa_model_v1_address_proto_rawDescGZIP() []byte {
	file_massa_model_v1_address_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_massa_model_v1_address_proto_rawDesc), len(file_massa_model_v1_address_proto_rawDesc)))
	})
	return file_massa_model_v1_address_proto_rawDescData
}

var file_massa_model_v1_address_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_massa_model_v1_address_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_massa_model_v1_address_proto_goTypes = []any{
	(AddressCategory)(0),  // 0: massa.model.v1.AddressCategory
	(*NativeAddress)(nil), // 1: massa.model.v1.NativeAddress
	(*Addresses)(nil),     // 2: massa.model.v1.Addresses
}
var file_massa_model_v1_address_proto_depIdxs = []int32{
	0, // 0: massa.model.v1.NativeAddress.category:type_name -> massa.model.v1.AddressCategory
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_massa_model_v1_address_proto_init() }
func file_massa_model_v1_address_proto_init() {
	if File_massa_model_v1_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_massa_model_v1_address_proto_rawDesc), len(file_massa_model_v1_address_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_address_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_address_proto_depIdxs,
		EnumInfos:         file_massa_model_v1_address_proto_enumTypes,
		MessageInfos:      file_massa_model_v1_address_proto_msgTypes,
	}.Build()
	File_massa_model_v1_address_proto = out.File
	file_massa_model_v1_address_proto_goTypes = nil
	file_massa_model_v1_address_proto_depIdxs = nil
}
