// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: massa/model/v1/amount.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NativeAmount is represented as a fraction so precision can be adjusted in
// the future. value = mantissa / (10^scale)
type NativeAmount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mantissa
	Mantissa uint64 `protobuf:"varint,1,opt,name=mantissa,proto3" json:"mantissa,omitempty"`
	// Scale
	Scale         uint32 `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NativeAmount) Reset() {
	*x = NativeAmount{}
	mi := &file_massa_model_v1_amount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeAmount) ProtoMessage() {}

func (x *NativeAmount) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_amount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeAmount.ProtoReflect.Descriptor instead.
func (*NativeAmount) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_amount_proto_rawDescGZIP(), []int{0}
}

func (x *NativeAmount) GetMantissa() uint64 {
	if x != nil {
		return x.Mantissa
	}
	return 0
}

func (x *NativeAmount) GetScale() uint32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

var File_massa_model_v1_amount_proto protoreflect.FileDescriptor

const file_massa_model_v1_amount_proto_rawDesc = "" +
	"\n" +
	"\x1bmassa/model/v1/amount.proto\x12\x0emassa.model.v1\"@\n" +
	"\fNativeAmount\x12\x1a\n" +
	"\bmantissa\x18\x01 \x01(\x04R\bmantissa\x12\x14\n" +
	"\x05scale\x18\x02 \x01(\rR\x05scaleB\xa5\x01\n" +
	"\x12com.massa.model.v1P\x01Z9github.com/jwmdev/massa-go/client/proto/massa/model/v1;v1\xa2\x02\x06MMODEL\xaa\x02\x12Com.Massa.Model.v1\xba\x02\x06MMODEL\xca\x02\x12Com\\Massa\\Model\\V1\xea\x02\x15Com::Massa::Model::V1b\x06proto3"

var (
	file_massa_model_v1_amount_proto_rawDescOnce sync.Once
	file_massa_model_v1_amount_proto_rawDescData []byte
)

func file_massa_model_v1_amount_proto_rawDescGZIP() []byte {
	file_massa_model_v1_amount_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_amount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_massa_model_v1_amount_proto_rawDesc), len(file_massa_model_v1_amount_proto_rawDesc)))
	})
	return file_massa_model_v1_amount_proto_rawDescData
}

var file_massa_model_v1_amount_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_massa_model_v1_amount_proto_goTypes = []any{
	(*NativeAmount)(nil), // 0: massa.model.v1.NativeAmount
}
var file_massa_model_v1_amount_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_massa_model_v1_amount_proto_init() }
func file_massa_model_v1_amount_proto_init() {
	if File_massa_model_v1_amount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_massa_model_v1_amount_proto_rawDesc), len(file_massa_model_v1_amount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_amount_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_amount_proto_depIdxs,
		MessageInfos:      file_massa_model_v1_amount_proto_msgTypes,
	}.Build()
	File_massa_model_v1_amount_proto = out.File
	file_massa_model_v1_amount_proto_goTypes = nil
	file_massa_model_v1_amount_proto_depIdxs = nil
}
