// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: massa/model/v1/block.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Possible statuses for a block
type BlockStatus int32

const (
	BlockStatus_BLOCK_STATUS_UNSPECIFIED                BlockStatus = 0 // Default enum value
	BlockStatus_BLOCK_STATUS_NON_FINAL_BLOCKCLIQUE      BlockStatus = 1 // The block is in the greatest clique (and not final)
	BlockStatus_BLOCK_STATUS_FINAL                      BlockStatus = 2 // The block is final
	BlockStatus_BLOCK_STATUS_NON_FINAL_ALTERNATE_CLIQUE BlockStatus = 3 // The block is candidate (active any clique but not final)
	BlockStatus_BLOCK_STATUS_DISCARDED                  BlockStatus = 4 // The block is discarded
)

// Enum value maps for BlockStatus.
var (
	BlockStatus_name = map[int32]string{
		0: "BLOCK_STATUS_UNSPECIFIED",
		1: "BLOCK_STATUS_NON_FINAL_BLOCKCLIQUE",
		2: "BLOCK_STATUS_FINAL",
		3: "BLOCK_STATUS_NON_FINAL_ALTERNATE_CLIQUE",
		4: "BLOCK_STATUS_DISCARDED",
	}
	BlockStatus_value = map[string]int32{
		"BLOCK_STATUS_UNSPECIFIED":                0,
		"BLOCK_STATUS_NON_FINAL_BLOCKCLIQUE":      1,
		"BLOCK_STATUS_FINAL":                      2,
		"BLOCK_STATUS_NON_FINAL_ALTERNATE_CLIQUE": 3,
		"BLOCK_STATUS_DISCARDED":                  4,
	}
)

func (x BlockStatus) Enum() *BlockStatus {
	p := new(BlockStatus)
	*p = x
	return p
}

func (x BlockStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_massa_model_v1_block_proto_enumTypes[0].Descriptor()
}

func (BlockStatus) Type() protoreflect.EnumType {
	return &file_massa_model_v1_block_proto_enumTypes[0]
}

func (x BlockStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockStatus.Descriptor instead.
func (BlockStatus) EnumDescriptor() ([]byte, []int) {
	return file_massa_model_v1_block_proto_rawDescGZIP(), []int{0}
}

// Block
type Block struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed header
	Header *SignedBlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Operations ids
	Operations    []string `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_massa_model_v1_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetHeader() *SignedBlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

// Filled block
type FilledBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed header
	Header *SignedBlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Operations
	Operations    []*FilledOperationEntry `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilledBlock) Reset() {
	*x = FilledBlock{}
	mi := &file_massa_model_v1_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilledBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilledBlock) ProtoMessage() {}

func (x *FilledBlock) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilledBlock.ProtoReflect.Descriptor instead.
func (*FilledBlock) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_block_proto_rawDescGZIP(), []int{1}
}

func (x *FilledBlock) GetHeader() *SignedBlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FilledBlock) GetOperations() []*FilledOperationEntry {
	if x != nil {
		return x.Operations
	}
	return nil
}

// Block header
type BlockHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current network version
	CurrentVersion uint32 `protobuf:"varint,1,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	// Announced network version(Optional)
	AnnouncedVersion *wrapperspb.UInt32Value `protobuf:"bytes,2,opt,name=announced_version,json=announcedVersion,proto3" json:"announced_version,omitempty"`
	// Slot
	Slot *Slot `protobuf:"bytes,3,opt,name=slot,proto3" json:"slot,omitempty"`
	// parents
	Parents []string `protobuf:"bytes,4,rep,name=parents,proto3" json:"parents,omitempty"`
	// All operations hash
	OperationsHash string `protobuf:"bytes,5,opt,name=operations_hash,json=operationsHash,proto3" json:"operations_hash,omitempty"`
	// Signed endorsements
	Endorsements []*SignedEndorsement `protobuf:"bytes,6,rep,name=endorsements,proto3" json:"endorsements,omitempty"`
	// Denunciations
	Denunciations []*Denunciation `protobuf:"bytes,7,rep,name=denunciations,proto3" json:"denunciations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_massa_model_v1_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_block_proto_rawDescGZIP(), []int{2}
}

func (x *BlockHeader) GetCurrentVersion() uint32 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *BlockHeader) GetAnnouncedVersion() *wrapperspb.UInt32Value {
	if x != nil {
		return x.AnnouncedVersion
	}
	return nil
}

func (x *BlockHeader) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *BlockHeader) GetParents() []string {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *BlockHeader) GetOperationsHash() string {
	if x != nil {
		return x.OperationsHash
	}
	return ""
}

func (x *BlockHeader) GetEndorsements() []*SignedEndorsement {
	if x != nil {
		return x.Endorsements
	}
	return nil
}

func (x *BlockHeader) GetDenunciations() []*Denunciation {
	if x != nil {
		return x.Denunciations
	}
	return nil
}

// Filled Operation Tuple
type FilledOperationEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation id
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Signed operation
	Operation     *SignedOperation `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilledOperationEntry) Reset() {
	*x = FilledOperationEntry{}
	mi := &file_massa_model_v1_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilledOperationEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilledOperationEntry) ProtoMessage() {}

func (x *FilledOperationEntry) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilledOperationEntry.ProtoReflect.Descriptor instead.
func (*FilledOperationEntry) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_block_proto_rawDescGZIP(), []int{3}
}

func (x *FilledOperationEntry) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *FilledOperationEntry) GetOperation() *SignedOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

// Signed block
type SignedBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block
	Content *Block `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// A cryptographically generated value using `serialized_data` and a public key.
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// The public-key component used in the generation of the signature
	ContentCreatorPubKey string `protobuf:"bytes,3,opt,name=content_creator_pub_key,json=contentCreatorPubKey,proto3" json:"content_creator_pub_key,omitempty"`
	// Derived from the same public key used to generate the signature
	ContentCreatorAddress string `protobuf:"bytes,4,opt,name=content_creator_address,json=contentCreatorAddress,proto3" json:"content_creator_address,omitempty"`
	// A secure hash of the non-malleable contents of a deterministic binary representation of the block header
	SecureHash string `protobuf:"bytes,5,opt,name=secure_hash,json=secureHash,proto3" json:"secure_hash,omitempty"`
	// The size of the serialized block in bytes
	SerializedSize uint64 `protobuf:"varint,6,opt,name=serialized_size,json=serializedSize,proto3" json:"serialized_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignedBlock) Reset() {
	*x = SignedBlock{}
	mi := &file_massa_model_v1_block_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedBlock) ProtoMessage() {}

func (x *SignedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_block_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedBlock.ProtoReflect.Descriptor instead.
func (*SignedBlock) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_block_proto_rawDescGZIP(), []int{4}
}

func (x *SignedBlock) GetContent() *Block {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SignedBlock) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignedBlock) GetContentCreatorPubKey() string {
	if x != nil {
		return x.ContentCreatorPubKey
	}
	return ""
}

func (x *SignedBlock) GetContentCreatorAddress() string {
	if x != nil {
		return x.ContentCreatorAddress
	}
	return ""
}

func (x *SignedBlock) GetSecureHash() string {
	if x != nil {
		return x.SecureHash
	}
	return ""
}

func (x *SignedBlock) GetSerializedSize() uint64 {
	if x != nil {
		return x.SerializedSize
	}
	return 0
}

// Signed block header
type SignedBlockHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BlockHeader
	Content *BlockHeader `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// A cryptographically generated value using `serialized_data` and a public key.
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// The public-key component used in the generation of the signature
	ContentCreatorPubKey string `protobuf:"bytes,3,opt,name=content_creator_pub_key,json=contentCreatorPubKey,proto3" json:"content_creator_pub_key,omitempty"`
	// Derived from the same public key used to generate the signature
	ContentCreatorAddress string `protobuf:"bytes,4,opt,name=content_creator_address,json=contentCreatorAddress,proto3" json:"content_creator_address,omitempty"`
	// A secure hash of the non-malleable contents of a deterministic binary representation of the block header
	SecureHash string `protobuf:"bytes,5,opt,name=secure_hash,json=secureHash,proto3" json:"secure_hash,omitempty"`
	// The size of the serialized block header in bytes
	SerializedSize uint64 `protobuf:"varint,6,opt,name=serialized_size,json=serializedSize,proto3" json:"serialized_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignedBlockHeader) Reset() {
	*x = SignedBlockHeader{}
	mi := &file_massa_model_v1_block_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedBlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedBlockHeader) ProtoMessage() {}

func (x *SignedBlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_block_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedBlockHeader.ProtoReflect.Descriptor instead.
func (*SignedBlockHeader) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_block_proto_rawDescGZIP(), []int{5}
}

func (x *SignedBlockHeader) GetContent() *BlockHeader {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SignedBlockHeader) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignedBlockHeader) GetContentCreatorPubKey() string {
	if x != nil {
		return x.ContentCreatorPubKey
	}
	return ""
}

func (x *SignedBlockHeader) GetContentCreatorAddress() string {
	if x != nil {
		return x.ContentCreatorAddress
	}
	return ""
}

func (x *SignedBlockHeader) GetSecureHash() string {
	if x != nil {
		return x.SecureHash
	}
	return ""
}

func (x *SignedBlockHeader) GetSerializedSize() uint64 {
	if x != nil {
		return x.SerializedSize
	}
	return 0
}

// A wrapper around a block with its metadata
type BlockWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The execution status of the block
	Status BlockStatus `protobuf:"varint,1,opt,name=status,proto3,enum=massa.model.v1.BlockStatus" json:"status,omitempty"`
	// The block object itself
	Block         *Block `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockWrapper) Reset() {
	*x = BlockWrapper{}
	mi := &file_massa_model_v1_block_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockWrapper) ProtoMessage() {}

func (x *BlockWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_block_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockWrapper.ProtoReflect.Descriptor instead.
func (*BlockWrapper) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_block_proto_rawDescGZIP(), []int{6}
}

func (x *BlockWrapper) GetStatus() BlockStatus {
	if x != nil {
		return x.Status
	}
	return BlockStatus_BLOCK_STATUS_UNSPECIFIED
}

func (x *BlockWrapper) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

// Informations about a block with its metadata
type BlockInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the block.
	BlockId string `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	// The execution status of the block
	Status        BlockStatus `protobuf:"varint,2,opt,name=status,proto3,enum=massa.model.v1.BlockStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockInfo) Reset() {
	*x = BlockInfo{}
	mi := &file_massa_model_v1_block_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockInfo) ProtoMessage() {}

func (x *BlockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_block_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockInfo.ProtoReflect.Descriptor instead.
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_block_proto_rawDescGZIP(), []int{7}
}

func (x *BlockInfo) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *BlockInfo) GetStatus() BlockStatus {
	if x != nil {
		return x.Status
	}
	return BlockStatus_BLOCK_STATUS_UNSPECIFIED
}

// BlockIds holds block ids
type BlockIds struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block ids
	BlockIds      []string `protobuf:"bytes,1,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockIds) Reset() {
	*x = BlockIds{}
	mi := &file_massa_model_v1_block_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockIds) ProtoMessage() {}

func (x *BlockIds) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_block_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockIds.ProtoReflect.Descriptor instead.
func (*BlockIds) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_block_proto_rawDescGZIP(), []int{8}
}

func (x *BlockIds) GetBlockIds() []string {
	if x != nil {
		return x.BlockIds
	}
	return nil
}

// Block parent tuple
type BlockParent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block id
	BlockId string `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	// Period
	Period        uint64 `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockParent) Reset() {
	*x = BlockParent{}
	mi := &file_massa_model_v1_block_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockParent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockParent) ProtoMessage() {}

func (x *BlockParent) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_block_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockParent.ProtoReflect.Descriptor instead.
func (*BlockParent) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_block_proto_rawDescGZIP(), []int{9}
}

func (x *BlockParent) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *BlockParent) GetPeriod() uint64 {
	if x != nil {
		return x.Period
	}
	return 0
}

var File_massa_model_v1_block_proto protoreflect.FileDescriptor

const file_massa_model_v1_block_proto_rawDesc = "" +
	"\n" +
	"\x1amassa/model/v1/block.proto\x12\x0emassa.model.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a!massa/model/v1/denunciation.proto\x1a massa/model/v1/endorsement.proto\x1a\x1emassa/model/v1/operation.proto\x1a\x19massa/model/v1/slot.proto\"b\n" +
	"\x05Block\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.massa.model.v1.SignedBlockHeaderR\x06header\x12\x1e\n" +
	"\n" +
	"operations\x18\x02 \x03(\tR\n" +
	"operations\"\x8e\x01\n" +
	"\vFilledBlock\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.massa.model.v1.SignedBlockHeaderR\x06header\x12D\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2$.massa.model.v1.FilledOperationEntryR\n" +
	"operations\"\xf9\x02\n" +
	"\vBlockHeader\x12'\n" +
	"\x0fcurrent_version\x18\x01 \x01(\rR\x0ecurrentVersion\x12I\n" +
	"\x11announced_version\x18\x02 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x10announcedVersion\x12(\n" +
	"\x04slot\x18\x03 \x01(\v2\x14.massa.model.v1.SlotR\x04slot\x12\x18\n" +
	"\aparents\x18\x04 \x03(\tR\aparents\x12'\n" +
	"\x0foperations_hash\x18\x05 \x01(\tR\x0eoperationsHash\x12E\n" +
	"\fendorsements\x18\x06 \x03(\v2!.massa.model.v1.SignedEndorsementR\fendorsements\x12B\n" +
	"\rdenunciations\x18\a \x03(\v2\x1c.massa.model.v1.DenunciationR\rdenunciations\"x\n" +
	"\x14FilledOperationEntry\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12=\n" +
	"\toperation\x18\x02 \x01(\v2\x1f.massa.model.v1.SignedOperationR\toperation\"\x95\x02\n" +
	"\vSignedBlock\x12/\n" +
	"\acontent\x18\x01 \x01(\v2\x15.massa.model.v1.BlockR\acontent\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x125\n" +
	"\x17content_creator_pub_key\x18\x03 \x01(\tR\x14contentCreatorPubKey\x126\n" +
	"\x17content_creator_address\x18\x04 \x01(\tR\x15contentCreatorAddress\x12\x1f\n" +
	"\vsecure_hash\x18\x05 \x01(\tR\n" +
	"secureHash\x12'\n" +
	"\x0fserialized_size\x18\x06 \x01(\x04R\x0eserializedSize\"\xa1\x02\n" +
	"\x11SignedBlockHeader\x125\n" +
	"\acontent\x18\x01 \x01(\v2\x1b.massa.model.v1.BlockHeaderR\acontent\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x125\n" +
	"\x17content_creator_pub_key\x18\x03 \x01(\tR\x14contentCreatorPubKey\x126\n" +
	"\x17content_creator_address\x18\x04 \x01(\tR\x15contentCreatorAddress\x12\x1f\n" +
	"\vsecure_hash\x18\x05 \x01(\tR\n" +
	"secureHash\x12'\n" +
	"\x0fserialized_size\x18\x06 \x01(\x04R\x0eserializedSize\"p\n" +
	"\fBlockWrapper\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.massa.model.v1.BlockStatusR\x06status\x12+\n" +
	"\x05block\x18\x02 \x01(\v2\x15.massa.model.v1.BlockR\x05block\"[\n" +
	"\tBlockInfo\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.massa.model.v1.BlockStatusR\x06status\"'\n" +
	"\bBlockIds\x12\x1b\n" +
	"\tblock_ids\x18\x01 \x03(\tR\bblockIds\"@\n" +
	"\vBlockParent\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\x04R\x06period*\xb4\x01\n" +
	"\vBlockStatus\x12\x1c\n" +
	"\x18BLOCK_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"BLOCK_STATUS_NON_FINAL_BLOCKCLIQUE\x10\x01\x12\x16\n" +
	"\x12BLOCK_STATUS_FINAL\x10\x02\x12+\n" +
	"'BLOCK_STATUS_NON_FINAL_ALTERNATE_CLIQUE\x10\x03\x12\x1a\n" +
	"\x16BLOCK_STATUS_DISCARDED\x10\x04B\xa8\x01\n" +
	"\x12com.massa.model.v1P\x01Z<github.com/nafsilabs/massa-go/client/proto/massa/model/v1;v1\xa2\x02\x06MMODEL\xaa\x02\x12Com.Massa.Model.v1\xba\x02\x06MMODEL\xca\x02\x12Com\\Massa\\Model\\V1\xea\x02\x15Com::Massa::Model::V1b\x06proto3"

var (
	file_massa_model_v1_block_proto_rawDescOnce sync.Once
	file_massa_model_v1_block_proto_rawDescData []byte
)

func file_massa_model_v1_block_proto_rawDescGZIP() []byte {
	file_massa_model_v1_block_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_massa_model_v1_block_proto_rawDesc), len(file_massa_model_v1_block_proto_rawDesc)))
	})
	return file_massa_model_v1_block_proto_rawDescData
}

var file_massa_model_v1_block_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_massa_model_v1_block_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_massa_model_v1_block_proto_goTypes = []any{
	(BlockStatus)(0),               // 0: massa.model.v1.BlockStatus
	(*Block)(nil),                  // 1: massa.model.v1.Block
	(*FilledBlock)(nil),            // 2: massa.model.v1.FilledBlock
	(*BlockHeader)(nil),            // 3: massa.model.v1.BlockHeader
	(*FilledOperationEntry)(nil),   // 4: massa.model.v1.FilledOperationEntry
	(*SignedBlock)(nil),            // 5: massa.model.v1.SignedBlock
	(*SignedBlockHeader)(nil),      // 6: massa.model.v1.SignedBlockHeader
	(*BlockWrapper)(nil),           // 7: massa.model.v1.BlockWrapper
	(*BlockInfo)(nil),              // 8: massa.model.v1.BlockInfo
	(*BlockIds)(nil),               // 9: massa.model.v1.BlockIds
	(*BlockParent)(nil),            // 10: massa.model.v1.BlockParent
	(*wrapperspb.UInt32Value)(nil), // 11: google.protobuf.UInt32Value
	(*Slot)(nil),                   // 12: massa.model.v1.Slot
	(*SignedEndorsement)(nil),      // 13: massa.model.v1.SignedEndorsement
	(*Denunciation)(nil),           // 14: massa.model.v1.Denunciation
	(*SignedOperation)(nil),        // 15: massa.model.v1.SignedOperation
}
var file_massa_model_v1_block_proto_depIdxs = []int32{
	6,  // 0: massa.model.v1.Block.header:type_name -> massa.model.v1.SignedBlockHeader
	6,  // 1: massa.model.v1.FilledBlock.header:type_name -> massa.model.v1.SignedBlockHeader
	4,  // 2: massa.model.v1.FilledBlock.operations:type_name -> massa.model.v1.FilledOperationEntry
	11, // 3: massa.model.v1.BlockHeader.announced_version:type_name -> google.protobuf.UInt32Value
	12, // 4: massa.model.v1.BlockHeader.slot:type_name -> massa.model.v1.Slot
	13, // 5: massa.model.v1.BlockHeader.endorsements:type_name -> massa.model.v1.SignedEndorsement
	14, // 6: massa.model.v1.BlockHeader.denunciations:type_name -> massa.model.v1.Denunciation
	15, // 7: massa.model.v1.FilledOperationEntry.operation:type_name -> massa.model.v1.SignedOperation
	1,  // 8: massa.model.v1.SignedBlock.content:type_name -> massa.model.v1.Block
	3,  // 9: massa.model.v1.SignedBlockHeader.content:type_name -> massa.model.v1.BlockHeader
	0,  // 10: massa.model.v1.BlockWrapper.status:type_name -> massa.model.v1.BlockStatus
	1,  // 11: massa.model.v1.BlockWrapper.block:type_name -> massa.model.v1.Block
	0,  // 12: massa.model.v1.BlockInfo.status:type_name -> massa.model.v1.BlockStatus
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_massa_model_v1_block_proto_init() }
func file_massa_model_v1_block_proto_init() {
	if File_massa_model_v1_block_proto != nil {
		return
	}
	file_massa_model_v1_denunciation_proto_init()
	file_massa_model_v1_endorsement_proto_init()
	file_massa_model_v1_operation_proto_init()
	file_massa_model_v1_slot_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_massa_model_v1_block_proto_rawDesc), len(file_massa_model_v1_block_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_block_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_block_proto_depIdxs,
		EnumInfos:         file_massa_model_v1_block_proto_enumTypes,
		MessageInfos:      file_massa_model_v1_block_proto_msgTypes,
	}.Build()
	File_massa_model_v1_block_proto = out.File
	file_massa_model_v1_block_proto_goTypes = nil
	file_massa_model_v1_block_proto_depIdxs = nil
}
