// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: massa/model/v1/commons.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Comparison result
type ComparisonResult int32

const (
	ComparisonResult_COMPARISON_RESULT_UNSPECIFIED ComparisonResult = 0
	// left is lower
	ComparisonResult_COMPARISON_RESULT_LOWER ComparisonResult = 1
	// left and right are equal
	ComparisonResult_COMPARISON_RESULT_EQUAL ComparisonResult = 2
	// left is greater
	ComparisonResult_COMPARISON_RESULT_GREATER ComparisonResult = 3
)

// Enum value maps for ComparisonResult.
var (
	ComparisonResult_name = map[int32]string{
		0: "COMPARISON_RESULT_UNSPECIFIED",
		1: "COMPARISON_RESULT_LOWER",
		2: "COMPARISON_RESULT_EQUAL",
		3: "COMPARISON_RESULT_GREATER",
	}
	ComparisonResult_value = map[string]int32{
		"COMPARISON_RESULT_UNSPECIFIED": 0,
		"COMPARISON_RESULT_LOWER":       1,
		"COMPARISON_RESULT_EQUAL":       2,
		"COMPARISON_RESULT_GREATER":     3,
	}
)

func (x ComparisonResult) Enum() *ComparisonResult {
	p := new(ComparisonResult)
	*p = x
	return p
}

func (x ComparisonResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComparisonResult) Descriptor() protoreflect.EnumDescriptor {
	return file_massa_model_v1_commons_proto_enumTypes[0].Descriptor()
}

func (ComparisonResult) Type() protoreflect.EnumType {
	return &file_massa_model_v1_commons_proto_enumTypes[0]
}

func (x ComparisonResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComparisonResult.Descriptor instead.
func (ComparisonResult) EnumDescriptor() ([]byte, []int) {
	return file_massa_model_v1_commons_proto_rawDescGZIP(), []int{0}
}

// Massa error
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The error code
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// A developer-facing error message, which should be in English
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_massa_model_v1_commons_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_commons_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_commons_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Empty
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_massa_model_v1_commons_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_commons_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_commons_proto_rawDescGZIP(), []int{1}
}

// BytesMapFieldEntry
type BytesMapFieldEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bytes key
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// bytes key
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BytesMapFieldEntry) Reset() {
	*x = BytesMapFieldEntry{}
	mi := &file_massa_model_v1_commons_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesMapFieldEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesMapFieldEntry) ProtoMessage() {}

func (x *BytesMapFieldEntry) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_commons_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesMapFieldEntry.ProtoReflect.Descriptor instead.
func (*BytesMapFieldEntry) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_commons_proto_rawDescGZIP(), []int{2}
}

func (x *BytesMapFieldEntry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BytesMapFieldEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Array of bytes wrapper
type ArrayOfBytesWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Repeated bytes
	Items         [][]byte `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayOfBytesWrapper) Reset() {
	*x = ArrayOfBytesWrapper{}
	mi := &file_massa_model_v1_commons_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayOfBytesWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayOfBytesWrapper) ProtoMessage() {}

func (x *ArrayOfBytesWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_commons_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayOfBytesWrapper.ProtoReflect.Descriptor instead.
func (*ArrayOfBytesWrapper) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_commons_proto_rawDescGZIP(), []int{3}
}

func (x *ArrayOfBytesWrapper) GetItems() [][]byte {
	if x != nil {
		return x.Items
	}
	return nil
}

// KeyPair
type KeyPair struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public key
	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Secret key
	SecretKey     string `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPair) Reset() {
	*x = KeyPair{}
	mi := &file_massa_model_v1_commons_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPair) ProtoMessage() {}

func (x *KeyPair) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_commons_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPair.ProtoReflect.Descriptor instead.
func (*KeyPair) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_commons_proto_rawDescGZIP(), []int{4}
}

func (x *KeyPair) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *KeyPair) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

var File_massa_model_v1_commons_proto protoreflect.FileDescriptor

const file_massa_model_v1_commons_proto_rawDesc = "" +
	"\n" +
	"\x1cmassa/model/v1/commons.proto\x12\x0emassa.model.v1\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\a\n" +
	"\x05Empty\"<\n" +
	"\x12BytesMapFieldEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"+\n" +
	"\x13ArrayOfBytesWrapper\x12\x14\n" +
	"\x05items\x18\x01 \x03(\fR\x05items\"G\n" +
	"\aKeyPair\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\tR\tsecretKey*\x8e\x01\n" +
	"\x10ComparisonResult\x12!\n" +
	"\x1dCOMPARISON_RESULT_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17COMPARISON_RESULT_LOWER\x10\x01\x12\x1b\n" +
	"\x17COMPARISON_RESULT_EQUAL\x10\x02\x12\x1d\n" +
	"\x19COMPARISON_RESULT_GREATER\x10\x03B\xa5\x01\n" +
	"\x12com.massa.model.v1P\x01Z9github.com/jwmdev/massa-go/client/proto/massa/model/v1;v1\xa2\x02\x06MMODEL\xaa\x02\x12Com.Massa.Model.v1\xba\x02\x06MMODEL\xca\x02\x12Com\\Massa\\Model\\V1\xea\x02\x15Com::Massa::Model::V1b\x06proto3"

var (
	file_massa_model_v1_commons_proto_rawDescOnce sync.Once
	file_massa_model_v1_commons_proto_rawDescData []byte
)

func file_massa_model_v1_commons_proto_rawDescGZIP() []byte {
	file_massa_model_v1_commons_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_commons_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_massa_model_v1_commons_proto_rawDesc), len(file_massa_model_v1_commons_proto_rawDesc)))
	})
	return file_massa_model_v1_commons_proto_rawDescData
}

var file_massa_model_v1_commons_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_massa_model_v1_commons_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_massa_model_v1_commons_proto_goTypes = []any{
	(ComparisonResult)(0),       // 0: massa.model.v1.ComparisonResult
	(*Error)(nil),               // 1: massa.model.v1.Error
	(*Empty)(nil),               // 2: massa.model.v1.Empty
	(*BytesMapFieldEntry)(nil),  // 3: massa.model.v1.BytesMapFieldEntry
	(*ArrayOfBytesWrapper)(nil), // 4: massa.model.v1.ArrayOfBytesWrapper
	(*KeyPair)(nil),             // 5: massa.model.v1.KeyPair
}
var file_massa_model_v1_commons_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_massa_model_v1_commons_proto_init() }
func file_massa_model_v1_commons_proto_init() {
	if File_massa_model_v1_commons_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_massa_model_v1_commons_proto_rawDesc), len(file_massa_model_v1_commons_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_commons_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_commons_proto_depIdxs,
		EnumInfos:         file_massa_model_v1_commons_proto_enumTypes,
		MessageInfos:      file_massa_model_v1_commons_proto_msgTypes,
	}.Build()
	File_massa_model_v1_commons_proto = out.File
	file_massa_model_v1_commons_proto_goTypes = nil
	file_massa_model_v1_commons_proto_depIdxs = nil
}
