// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: massa/model/v1/datastore.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddressKeys holds a list of addresses - keys
type AddressKeysEntries struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of address- key entries
	AddressKeyEntries []*AddressKeyEntry `protobuf:"bytes,1,rep,name=address_key_entries,json=addressKeyEntries,proto3" json:"address_key_entries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddressKeysEntries) Reset() {
	*x = AddressKeysEntries{}
	mi := &file_massa_model_v1_datastore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressKeysEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressKeysEntries) ProtoMessage() {}

func (x *AddressKeysEntries) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_datastore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressKeysEntries.ProtoReflect.Descriptor instead.
func (*AddressKeysEntries) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_datastore_proto_rawDescGZIP(), []int{0}
}

func (x *AddressKeysEntries) GetAddressKeyEntries() []*AddressKeyEntry {
	if x != nil {
		return x.AddressKeyEntries
	}
	return nil
}

// AddressKeyEntry
type AddressKeyEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Associated address of the entry
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Datastore key
	Key           []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressKeyEntry) Reset() {
	*x = AddressKeyEntry{}
	mi := &file_massa_model_v1_datastore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressKeyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressKeyEntry) ProtoMessage() {}

func (x *AddressKeyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_datastore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressKeyEntry.ProtoReflect.Descriptor instead.
func (*AddressKeyEntry) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_datastore_proto_rawDescGZIP(), []int{1}
}

func (x *AddressKeyEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressKeyEntry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// DatastoreEntry
type DatastoreEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// final datastore entry value
	FinalValue []byte `protobuf:"bytes,1,opt,name=final_value,json=finalValue,proto3" json:"final_value,omitempty"`
	// candidate_value datastore entry value
	CandidateValue []byte `protobuf:"bytes,2,opt,name=candidate_value,json=candidateValue,proto3" json:"candidate_value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DatastoreEntry) Reset() {
	*x = DatastoreEntry{}
	mi := &file_massa_model_v1_datastore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatastoreEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatastoreEntry) ProtoMessage() {}

func (x *DatastoreEntry) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_datastore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatastoreEntry.ProtoReflect.Descriptor instead.
func (*DatastoreEntry) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_datastore_proto_rawDescGZIP(), []int{2}
}

func (x *DatastoreEntry) GetFinalValue() []byte {
	if x != nil {
		return x.FinalValue
	}
	return nil
}

func (x *DatastoreEntry) GetCandidateValue() []byte {
	if x != nil {
		return x.CandidateValue
	}
	return nil
}

var File_massa_model_v1_datastore_proto protoreflect.FileDescriptor

const file_massa_model_v1_datastore_proto_rawDesc = "" +
	"\n" +
	"\x1emassa/model/v1/datastore.proto\x12\x0emassa.model.v1\"e\n" +
	"\x12AddressKeysEntries\x12O\n" +
	"\x13address_key_entries\x18\x01 \x03(\v2\x1f.massa.model.v1.AddressKeyEntryR\x11addressKeyEntries\"=\n" +
	"\x0fAddressKeyEntry\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"Z\n" +
	"\x0eDatastoreEntry\x12\x1f\n" +
	"\vfinal_value\x18\x01 \x01(\fR\n" +
	"finalValue\x12'\n" +
	"\x0fcandidate_value\x18\x02 \x01(\fR\x0ecandidateValueB\xa5\x01\n" +
	"\x12com.massa.model.v1P\x01Z9github.com/jwmdev/massa-go/client/proto/massa/model/v1;v1\xa2\x02\x06MMODEL\xaa\x02\x12Com.Massa.Model.v1\xba\x02\x06MMODEL\xca\x02\x12Com\\Massa\\Model\\V1\xea\x02\x15Com::Massa::Model::V1b\x06proto3"

var (
	file_massa_model_v1_datastore_proto_rawDescOnce sync.Once
	file_massa_model_v1_datastore_proto_rawDescData []byte
)

func file_massa_model_v1_datastore_proto_rawDescGZIP() []byte {
	file_massa_model_v1_datastore_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_datastore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_massa_model_v1_datastore_proto_rawDesc), len(file_massa_model_v1_datastore_proto_rawDesc)))
	})
	return file_massa_model_v1_datastore_proto_rawDescData
}

var file_massa_model_v1_datastore_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_massa_model_v1_datastore_proto_goTypes = []any{
	(*AddressKeysEntries)(nil), // 0: massa.model.v1.AddressKeysEntries
	(*AddressKeyEntry)(nil),    // 1: massa.model.v1.AddressKeyEntry
	(*DatastoreEntry)(nil),     // 2: massa.model.v1.DatastoreEntry
}
var file_massa_model_v1_datastore_proto_depIdxs = []int32{
	1, // 0: massa.model.v1.AddressKeysEntries.address_key_entries:type_name -> massa.model.v1.AddressKeyEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_massa_model_v1_datastore_proto_init() }
func file_massa_model_v1_datastore_proto_init() {
	if File_massa_model_v1_datastore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_massa_model_v1_datastore_proto_rawDesc), len(file_massa_model_v1_datastore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_datastore_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_datastore_proto_depIdxs,
		MessageInfos:      file_massa_model_v1_datastore_proto_msgTypes,
	}.Build()
	File_massa_model_v1_datastore_proto = out.File
	file_massa_model_v1_datastore_proto_goTypes = nil
	file_massa_model_v1_datastore_proto_depIdxs = nil
}
