// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: massa/model/v1/denunciation.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Denunciation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BlockHeaderDenunciation or EndorsementDenunciation
	//
	// Types that are valid to be assigned to Entry:
	//
	//	*Denunciation_BlockHeader
	//	*Denunciation_Endorsement
	//	*Denunciation_Address
	Entry         isDenunciation_Entry `protobuf_oneof:"entry"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Denunciation) Reset() {
	*x = Denunciation{}
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Denunciation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Denunciation) ProtoMessage() {}

func (x *Denunciation) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Denunciation.ProtoReflect.Descriptor instead.
func (*Denunciation) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_denunciation_proto_rawDescGZIP(), []int{0}
}

func (x *Denunciation) GetEntry() isDenunciation_Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *Denunciation) GetBlockHeader() *BlockHeaderDenunciation {
	if x != nil {
		if x, ok := x.Entry.(*Denunciation_BlockHeader); ok {
			return x.BlockHeader
		}
	}
	return nil
}

func (x *Denunciation) GetEndorsement() *EndorsementDenunciation {
	if x != nil {
		if x, ok := x.Entry.(*Denunciation_Endorsement); ok {
			return x.Endorsement
		}
	}
	return nil
}

func (x *Denunciation) GetAddress() *DenunciationAddress {
	if x != nil {
		if x, ok := x.Entry.(*Denunciation_Address); ok {
			return x.Address
		}
	}
	return nil
}

type isDenunciation_Entry interface {
	isDenunciation_Entry()
}

type Denunciation_BlockHeader struct {
	// Denunciation block header
	BlockHeader *BlockHeaderDenunciation `protobuf:"bytes,1,opt,name=block_header,json=blockHeader,proto3,oneof"`
}

type Denunciation_Endorsement struct {
	// Denunciation endorsement
	Endorsement *EndorsementDenunciation `protobuf:"bytes,2,opt,name=endorsement,proto3,oneof"`
}

type Denunciation_Address struct {
	// Denunciation address
	Address *DenunciationAddress `protobuf:"bytes,3,opt,name=address,proto3,oneof"`
}

func (*Denunciation_BlockHeader) isDenunciation_Entry() {}

func (*Denunciation_Endorsement) isDenunciation_Entry() {}

func (*Denunciation_Address) isDenunciation_Entry() {}

type BlockHeaderDenunciation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Denunciation public key
	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Denunciation slot
	Slot *Slot `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	// Denunciation hash 1
	Hash_1 string `protobuf:"bytes,3,opt,name=hash_1,json=hash1,proto3" json:"hash_1,omitempty"`
	// Denunciation hash 2
	Hash_2 string `protobuf:"bytes,4,opt,name=hash_2,json=hash2,proto3" json:"hash_2,omitempty"`
	// Denunciation sig 1
	Signature_1 string `protobuf:"bytes,5,opt,name=signature_1,json=signature1,proto3" json:"signature_1,omitempty"`
	// Denunciation sig 2
	Signature_2   string `protobuf:"bytes,6,opt,name=signature_2,json=signature2,proto3" json:"signature_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHeaderDenunciation) Reset() {
	*x = BlockHeaderDenunciation{}
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeaderDenunciation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeaderDenunciation) ProtoMessage() {}

func (x *BlockHeaderDenunciation) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeaderDenunciation.ProtoReflect.Descriptor instead.
func (*BlockHeaderDenunciation) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_denunciation_proto_rawDescGZIP(), []int{1}
}

func (x *BlockHeaderDenunciation) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *BlockHeaderDenunciation) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *BlockHeaderDenunciation) GetHash_1() string {
	if x != nil {
		return x.Hash_1
	}
	return ""
}

func (x *BlockHeaderDenunciation) GetHash_2() string {
	if x != nil {
		return x.Hash_2
	}
	return ""
}

func (x *BlockHeaderDenunciation) GetSignature_1() string {
	if x != nil {
		return x.Signature_1
	}
	return ""
}

func (x *BlockHeaderDenunciation) GetSignature_2() string {
	if x != nil {
		return x.Signature_2
	}
	return ""
}

type EndorsementDenunciation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Denunciation public key
	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Denunciation slot
	Slot *Slot `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	// Denunciation index
	Index uint32 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	// Denunciation hash 1
	Hash_1 string `protobuf:"bytes,4,opt,name=hash_1,json=hash1,proto3" json:"hash_1,omitempty"`
	// Denunciation hash 2
	Hash_2 string `protobuf:"bytes,5,opt,name=hash_2,json=hash2,proto3" json:"hash_2,omitempty"`
	// Denunciation sig 1
	Signature_1 string `protobuf:"bytes,6,opt,name=signature_1,json=signature1,proto3" json:"signature_1,omitempty"`
	// Denunciation sig 2
	Signature_2   string `protobuf:"bytes,7,opt,name=signature_2,json=signature2,proto3" json:"signature_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndorsementDenunciation) Reset() {
	*x = EndorsementDenunciation{}
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndorsementDenunciation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndorsementDenunciation) ProtoMessage() {}

func (x *EndorsementDenunciation) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndorsementDenunciation.ProtoReflect.Descriptor instead.
func (*EndorsementDenunciation) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_denunciation_proto_rawDescGZIP(), []int{2}
}

func (x *EndorsementDenunciation) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *EndorsementDenunciation) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *EndorsementDenunciation) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EndorsementDenunciation) GetHash_1() string {
	if x != nil {
		return x.Hash_1
	}
	return ""
}

func (x *EndorsementDenunciation) GetHash_2() string {
	if x != nil {
		return x.Hash_2
	}
	return ""
}

func (x *EndorsementDenunciation) GetSignature_1() string {
	if x != nil {
		return x.Signature_1
	}
	return ""
}

func (x *EndorsementDenunciation) GetSignature_2() string {
	if x != nil {
		return x.Signature_2
	}
	return ""
}

// Index for Denunciations in collections (e.g. like a HashMap...)
type DenunciationIndex struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DenunciationBlockHeader or DenunciationEndorsement
	//
	// Types that are valid to be assigned to Entry:
	//
	//	*DenunciationIndex_BlockHeader
	//	*DenunciationIndex_Endorsement
	Entry         isDenunciationIndex_Entry `protobuf_oneof:"entry"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenunciationIndex) Reset() {
	*x = DenunciationIndex{}
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenunciationIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenunciationIndex) ProtoMessage() {}

func (x *DenunciationIndex) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenunciationIndex.ProtoReflect.Descriptor instead.
func (*DenunciationIndex) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_denunciation_proto_rawDescGZIP(), []int{3}
}

func (x *DenunciationIndex) GetEntry() isDenunciationIndex_Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *DenunciationIndex) GetBlockHeader() *DenunciationBlockHeader {
	if x != nil {
		if x, ok := x.Entry.(*DenunciationIndex_BlockHeader); ok {
			return x.BlockHeader
		}
	}
	return nil
}

func (x *DenunciationIndex) GetEndorsement() *DenunciationEndorsement {
	if x != nil {
		if x, ok := x.Entry.(*DenunciationIndex_Endorsement); ok {
			return x.Endorsement
		}
	}
	return nil
}

type isDenunciationIndex_Entry interface {
	isDenunciationIndex_Entry()
}

type DenunciationIndex_BlockHeader struct {
	// Denunciation block header
	BlockHeader *DenunciationBlockHeader `protobuf:"bytes,1,opt,name=block_header,json=blockHeader,proto3,oneof"`
}

type DenunciationIndex_Endorsement struct {
	// Denunciation endorsement
	Endorsement *DenunciationEndorsement `protobuf:"bytes,2,opt,name=endorsement,proto3,oneof"`
}

func (*DenunciationIndex_BlockHeader) isDenunciationIndex_Entry() {}

func (*DenunciationIndex_Endorsement) isDenunciationIndex_Entry() {}

// Variant for Block header denunciation index
type DenunciationBlockHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Denunciation slot
	Slot          *Slot `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenunciationBlockHeader) Reset() {
	*x = DenunciationBlockHeader{}
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenunciationBlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenunciationBlockHeader) ProtoMessage() {}

func (x *DenunciationBlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenunciationBlockHeader.ProtoReflect.Descriptor instead.
func (*DenunciationBlockHeader) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_denunciation_proto_rawDescGZIP(), []int{4}
}

func (x *DenunciationBlockHeader) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

// Variant for Endorsement denunciation index
type DenunciationEndorsement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Denounciation slot
	Slot *Slot `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// Denounciation index
	Index         uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenunciationEndorsement) Reset() {
	*x = DenunciationEndorsement{}
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenunciationEndorsement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenunciationEndorsement) ProtoMessage() {}

func (x *DenunciationEndorsement) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenunciationEndorsement.ProtoReflect.Descriptor instead.
func (*DenunciationEndorsement) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_denunciation_proto_rawDescGZIP(), []int{5}
}

func (x *DenunciationEndorsement) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *DenunciationEndorsement) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type DenunciationAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target address
	AddressDenounced string `protobuf:"bytes,1,opt,name=address_denounced,json=addressDenounced,proto3" json:"address_denounced,omitempty"`
	// slot
	Slot *Slot `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	// amount slashed
	Slashed       *NativeAmount `protobuf:"bytes,4,opt,name=slashed,proto3" json:"slashed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenunciationAddress) Reset() {
	*x = DenunciationAddress{}
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenunciationAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenunciationAddress) ProtoMessage() {}

func (x *DenunciationAddress) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenunciationAddress.ProtoReflect.Descriptor instead.
func (*DenunciationAddress) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_denunciation_proto_rawDescGZIP(), []int{6}
}

func (x *DenunciationAddress) GetAddressDenounced() string {
	if x != nil {
		return x.AddressDenounced
	}
	return ""
}

func (x *DenunciationAddress) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *DenunciationAddress) GetSlashed() *NativeAmount {
	if x != nil {
		return x.Slashed
	}
	return nil
}

var File_massa_model_v1_denunciation_proto protoreflect.FileDescriptor

const file_massa_model_v1_denunciation_proto_rawDesc = "" +
	"\n" +
	"!massa/model/v1/denunciation.proto\x12\x0emassa.model.v1\x1a\x1bmassa/model/v1/amount.proto\x1a\x19massa/model/v1/slot.proto\"\xf3\x01\n" +
	"\fDenunciation\x12L\n" +
	"\fblock_header\x18\x01 \x01(\v2'.massa.model.v1.BlockHeaderDenunciationH\x00R\vblockHeader\x12K\n" +
	"\vendorsement\x18\x02 \x01(\v2'.massa.model.v1.EndorsementDenunciationH\x00R\vendorsement\x12?\n" +
	"\aaddress\x18\x03 \x01(\v2#.massa.model.v1.DenunciationAddressH\x00R\aaddressB\a\n" +
	"\x05entry\"\xd2\x01\n" +
	"\x17BlockHeaderDenunciation\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12(\n" +
	"\x04slot\x18\x02 \x01(\v2\x14.massa.model.v1.SlotR\x04slot\x12\x15\n" +
	"\x06hash_1\x18\x03 \x01(\tR\x05hash1\x12\x15\n" +
	"\x06hash_2\x18\x04 \x01(\tR\x05hash2\x12\x1f\n" +
	"\vsignature_1\x18\x05 \x01(\tR\n" +
	"signature1\x12\x1f\n" +
	"\vsignature_2\x18\x06 \x01(\tR\n" +
	"signature2\"\xe8\x01\n" +
	"\x17EndorsementDenunciation\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12(\n" +
	"\x04slot\x18\x02 \x01(\v2\x14.massa.model.v1.SlotR\x04slot\x12\x14\n" +
	"\x05index\x18\x03 \x01(\rR\x05index\x12\x15\n" +
	"\x06hash_1\x18\x04 \x01(\tR\x05hash1\x12\x15\n" +
	"\x06hash_2\x18\x05 \x01(\tR\x05hash2\x12\x1f\n" +
	"\vsignature_1\x18\x06 \x01(\tR\n" +
	"signature1\x12\x1f\n" +
	"\vsignature_2\x18\a \x01(\tR\n" +
	"signature2\"\xb7\x01\n" +
	"\x11DenunciationIndex\x12L\n" +
	"\fblock_header\x18\x01 \x01(\v2'.massa.model.v1.DenunciationBlockHeaderH\x00R\vblockHeader\x12K\n" +
	"\vendorsement\x18\x02 \x01(\v2'.massa.model.v1.DenunciationEndorsementH\x00R\vendorsementB\a\n" +
	"\x05entry\"C\n" +
	"\x17DenunciationBlockHeader\x12(\n" +
	"\x04slot\x18\x01 \x01(\v2\x14.massa.model.v1.SlotR\x04slot\"Y\n" +
	"\x17DenunciationEndorsement\x12(\n" +
	"\x04slot\x18\x01 \x01(\v2\x14.massa.model.v1.SlotR\x04slot\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"\xa4\x01\n" +
	"\x13DenunciationAddress\x12+\n" +
	"\x11address_denounced\x18\x01 \x01(\tR\x10addressDenounced\x12(\n" +
	"\x04slot\x18\x02 \x01(\v2\x14.massa.model.v1.SlotR\x04slot\x126\n" +
	"\aslashed\x18\x04 \x01(\v2\x1c.massa.model.v1.NativeAmountR\aslashedB\xa8\x01\n" +
	"\x12com.massa.model.v1P\x01Z<github.com/nafsilabs/massa-go/client/proto/massa/model/v1;v1\xa2\x02\x06MMODEL\xaa\x02\x12Com.Massa.Model.v1\xba\x02\x06MMODEL\xca\x02\x12Com\\Massa\\Model\\V1\xea\x02\x15Com::Massa::Model::V1b\x06proto3"

var (
	file_massa_model_v1_denunciation_proto_rawDescOnce sync.Once
	file_massa_model_v1_denunciation_proto_rawDescData []byte
)

func file_massa_model_v1_denunciation_proto_rawDescGZIP() []byte {
	file_massa_model_v1_denunciation_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_denunciation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_massa_model_v1_denunciation_proto_rawDesc), len(file_massa_model_v1_denunciation_proto_rawDesc)))
	})
	return file_massa_model_v1_denunciation_proto_rawDescData
}

var file_massa_model_v1_denunciation_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_massa_model_v1_denunciation_proto_goTypes = []any{
	(*Denunciation)(nil),            // 0: massa.model.v1.Denunciation
	(*BlockHeaderDenunciation)(nil), // 1: massa.model.v1.BlockHeaderDenunciation
	(*EndorsementDenunciation)(nil), // 2: massa.model.v1.EndorsementDenunciation
	(*DenunciationIndex)(nil),       // 3: massa.model.v1.DenunciationIndex
	(*DenunciationBlockHeader)(nil), // 4: massa.model.v1.DenunciationBlockHeader
	(*DenunciationEndorsement)(nil), // 5: massa.model.v1.DenunciationEndorsement
	(*DenunciationAddress)(nil),     // 6: massa.model.v1.DenunciationAddress
	(*Slot)(nil),                    // 7: massa.model.v1.Slot
	(*NativeAmount)(nil),            // 8: massa.model.v1.NativeAmount
}
var file_massa_model_v1_denunciation_proto_depIdxs = []int32{
	1,  // 0: massa.model.v1.Denunciation.block_header:type_name -> massa.model.v1.BlockHeaderDenunciation
	2,  // 1: massa.model.v1.Denunciation.endorsement:type_name -> massa.model.v1.EndorsementDenunciation
	6,  // 2: massa.model.v1.Denunciation.address:type_name -> massa.model.v1.DenunciationAddress
	7,  // 3: massa.model.v1.BlockHeaderDenunciation.slot:type_name -> massa.model.v1.Slot
	7,  // 4: massa.model.v1.EndorsementDenunciation.slot:type_name -> massa.model.v1.Slot
	4,  // 5: massa.model.v1.DenunciationIndex.block_header:type_name -> massa.model.v1.DenunciationBlockHeader
	5,  // 6: massa.model.v1.DenunciationIndex.endorsement:type_name -> massa.model.v1.DenunciationEndorsement
	7,  // 7: massa.model.v1.DenunciationBlockHeader.slot:type_name -> massa.model.v1.Slot
	7,  // 8: massa.model.v1.DenunciationEndorsement.slot:type_name -> massa.model.v1.Slot
	7,  // 9: massa.model.v1.DenunciationAddress.slot:type_name -> massa.model.v1.Slot
	8,  // 10: massa.model.v1.DenunciationAddress.slashed:type_name -> massa.model.v1.NativeAmount
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_massa_model_v1_denunciation_proto_init() }
func file_massa_model_v1_denunciation_proto_init() {
	if File_massa_model_v1_denunciation_proto != nil {
		return
	}
	file_massa_model_v1_amount_proto_init()
	file_massa_model_v1_slot_proto_init()
	file_massa_model_v1_denunciation_proto_msgTypes[0].OneofWrappers = []any{
		(*Denunciation_BlockHeader)(nil),
		(*Denunciation_Endorsement)(nil),
		(*Denunciation_Address)(nil),
	}
	file_massa_model_v1_denunciation_proto_msgTypes[3].OneofWrappers = []any{
		(*DenunciationIndex_BlockHeader)(nil),
		(*DenunciationIndex_Endorsement)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_massa_model_v1_denunciation_proto_rawDesc), len(file_massa_model_v1_denunciation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_denunciation_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_denunciation_proto_depIdxs,
		MessageInfos:      file_massa_model_v1_denunciation_proto_msgTypes,
	}.Build()
	File_massa_model_v1_denunciation_proto = out.File
	file_massa_model_v1_denunciation_proto_goTypes = nil
	file_massa_model_v1_denunciation_proto_depIdxs = nil
}
