// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: massa/model/v1/draw.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Slot draw
type SlotDraw struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Slot
	Slot *Slot `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// Block producer address (Optional)
	BlockProducer *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=block_producer,json=blockProducer,proto3" json:"block_producer,omitempty"`
	// Endorsement draws
	EndorsementDraws []*EndorsementDraw `protobuf:"bytes,3,rep,name=endorsement_draws,json=endorsementDraws,proto3" json:"endorsement_draws,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SlotDraw) Reset() {
	*x = SlotDraw{}
	mi := &file_massa_model_v1_draw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotDraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotDraw) ProtoMessage() {}

func (x *SlotDraw) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_draw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotDraw.ProtoReflect.Descriptor instead.
func (*SlotDraw) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_draw_proto_rawDescGZIP(), []int{0}
}

func (x *SlotDraw) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *SlotDraw) GetBlockProducer() *wrapperspb.StringValue {
	if x != nil {
		return x.BlockProducer
	}
	return nil
}

func (x *SlotDraw) GetEndorsementDraws() []*EndorsementDraw {
	if x != nil {
		return x.EndorsementDraws
	}
	return nil
}

// Endorsement draw
type EndorsementDraw struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endorsement index
	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Producer address
	Producer      string `protobuf:"bytes,2,opt,name=producer,proto3" json:"producer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndorsementDraw) Reset() {
	*x = EndorsementDraw{}
	mi := &file_massa_model_v1_draw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndorsementDraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndorsementDraw) ProtoMessage() {}

func (x *EndorsementDraw) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_draw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndorsementDraw.ProtoReflect.Descriptor instead.
func (*EndorsementDraw) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_draw_proto_rawDescGZIP(), []int{1}
}

func (x *EndorsementDraw) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EndorsementDraw) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

var File_massa_model_v1_draw_proto protoreflect.FileDescriptor

const file_massa_model_v1_draw_proto_rawDesc = "" +
	"\n" +
	"\x19massa/model/v1/draw.proto\x12\x0emassa.model.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x19massa/model/v1/slot.proto\"\xc7\x01\n" +
	"\bSlotDraw\x12(\n" +
	"\x04slot\x18\x01 \x01(\v2\x14.massa.model.v1.SlotR\x04slot\x12C\n" +
	"\x0eblock_producer\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\rblockProducer\x12L\n" +
	"\x11endorsement_draws\x18\x03 \x03(\v2\x1f.massa.model.v1.EndorsementDrawR\x10endorsementDraws\"C\n" +
	"\x0fEndorsementDraw\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x1a\n" +
	"\bproducer\x18\x02 \x01(\tR\bproducerB\xa8\x01\n" +
	"\x12com.massa.model.v1P\x01Z<github.com/nafsilabs/massa-go/client/proto/massa/model/v1;v1\xa2\x02\x06MMODEL\xaa\x02\x12Com.Massa.Model.v1\xba\x02\x06MMODEL\xca\x02\x12Com\\Massa\\Model\\V1\xea\x02\x15Com::Massa::Model::V1b\x06proto3"

var (
	file_massa_model_v1_draw_proto_rawDescOnce sync.Once
	file_massa_model_v1_draw_proto_rawDescData []byte
)

func file_massa_model_v1_draw_proto_rawDescGZIP() []byte {
	file_massa_model_v1_draw_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_draw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_massa_model_v1_draw_proto_rawDesc), len(file_massa_model_v1_draw_proto_rawDesc)))
	})
	return file_massa_model_v1_draw_proto_rawDescData
}

var file_massa_model_v1_draw_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_massa_model_v1_draw_proto_goTypes = []any{
	(*SlotDraw)(nil),               // 0: massa.model.v1.SlotDraw
	(*EndorsementDraw)(nil),        // 1: massa.model.v1.EndorsementDraw
	(*Slot)(nil),                   // 2: massa.model.v1.Slot
	(*wrapperspb.StringValue)(nil), // 3: google.protobuf.StringValue
}
var file_massa_model_v1_draw_proto_depIdxs = []int32{
	2, // 0: massa.model.v1.SlotDraw.slot:type_name -> massa.model.v1.Slot
	3, // 1: massa.model.v1.SlotDraw.block_producer:type_name -> google.protobuf.StringValue
	1, // 2: massa.model.v1.SlotDraw.endorsement_draws:type_name -> massa.model.v1.EndorsementDraw
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_massa_model_v1_draw_proto_init() }
func file_massa_model_v1_draw_proto_init() {
	if File_massa_model_v1_draw_proto != nil {
		return
	}
	file_massa_model_v1_slot_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_massa_model_v1_draw_proto_rawDesc), len(file_massa_model_v1_draw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_draw_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_draw_proto_depIdxs,
		MessageInfos:      file_massa_model_v1_draw_proto_msgTypes,
	}.Build()
	File_massa_model_v1_draw_proto = out.File
	file_massa_model_v1_draw_proto_goTypes = nil
	file_massa_model_v1_draw_proto_depIdxs = nil
}
