// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: massa/model/v1/endorsement.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An endorsement, as sent in the network
type Endorsement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Slot in which the endorsement can be included
	Slot *Slot `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// Endorsement index inside the including block
	Index uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// Hash of endorsed block
	// This is the parent in thread `self.slot.thread` of the block in which the endorsement is included
	EndorsedBlock string `protobuf:"bytes,3,opt,name=endorsed_block,json=endorsedBlock,proto3" json:"endorsed_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endorsement) Reset() {
	*x = Endorsement{}
	mi := &file_massa_model_v1_endorsement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endorsement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endorsement) ProtoMessage() {}

func (x *Endorsement) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_endorsement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endorsement.ProtoReflect.Descriptor instead.
func (*Endorsement) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_endorsement_proto_rawDescGZIP(), []int{0}
}

func (x *Endorsement) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *Endorsement) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Endorsement) GetEndorsedBlock() string {
	if x != nil {
		return x.EndorsedBlock
	}
	return ""
}

// Signed endorsement
type SignedEndorsement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endorsement
	Content *Endorsement `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// A cryptographically generated value using `serialized_data` and a public key.
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// The public-key component used in the generation of the signature
	ContentCreatorPubKey string `protobuf:"bytes,3,opt,name=content_creator_pub_key,json=contentCreatorPubKey,proto3" json:"content_creator_pub_key,omitempty"`
	// Derived from the same public key used to generate the signature
	ContentCreatorAddress string `protobuf:"bytes,4,opt,name=content_creator_address,json=contentCreatorAddress,proto3" json:"content_creator_address,omitempty"`
	// A secure hash of the non-malleable contents of a deterministic binary representation of the block header
	SecureHash string `protobuf:"bytes,5,opt,name=secure_hash,json=secureHash,proto3" json:"secure_hash,omitempty"`
	// The size of the serialized endorsement in bytes
	SerializedSize uint64 `protobuf:"varint,6,opt,name=serialized_size,json=serializedSize,proto3" json:"serialized_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignedEndorsement) Reset() {
	*x = SignedEndorsement{}
	mi := &file_massa_model_v1_endorsement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedEndorsement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedEndorsement) ProtoMessage() {}

func (x *SignedEndorsement) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_endorsement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedEndorsement.ProtoReflect.Descriptor instead.
func (*SignedEndorsement) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_endorsement_proto_rawDescGZIP(), []int{1}
}

func (x *SignedEndorsement) GetContent() *Endorsement {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SignedEndorsement) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignedEndorsement) GetContentCreatorPubKey() string {
	if x != nil {
		return x.ContentCreatorPubKey
	}
	return ""
}

func (x *SignedEndorsement) GetContentCreatorAddress() string {
	if x != nil {
		return x.ContentCreatorAddress
	}
	return ""
}

func (x *SignedEndorsement) GetSecureHash() string {
	if x != nil {
		return x.SecureHash
	}
	return ""
}

func (x *SignedEndorsement) GetSerializedSize() uint64 {
	if x != nil {
		return x.SerializedSize
	}
	return 0
}

// EndorsementIds holds endorsements ids
type EndorsementIds struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endorsements ids
	EndorsementIds []string `protobuf:"bytes,1,rep,name=endorsement_ids,json=endorsementIds,proto3" json:"endorsement_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EndorsementIds) Reset() {
	*x = EndorsementIds{}
	mi := &file_massa_model_v1_endorsement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndorsementIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndorsementIds) ProtoMessage() {}

func (x *EndorsementIds) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_endorsement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndorsementIds.ProtoReflect.Descriptor instead.
func (*EndorsementIds) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_endorsement_proto_rawDescGZIP(), []int{2}
}

func (x *EndorsementIds) GetEndorsementIds() []string {
	if x != nil {
		return x.EndorsementIds
	}
	return nil
}

// A wrapper around an endorsement with its metadata
type EndorsementWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the endorsement is still in pool
	InPool bool `protobuf:"varint,1,opt,name=in_pool,json=inPool,proto3" json:"in_pool,omitempty"`
	// The endorsement appears in `in_blocks`
	// If it appears in multiple blocks, these blocks are in different cliques
	InBlocks []string `protobuf:"bytes,2,rep,name=in_blocks,json=inBlocks,proto3" json:"in_blocks,omitempty"`
	// Whether the the endorsement is final (for example in a final block)
	IsFinal bool `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// The endorsement itself
	Endorsement   *SignedEndorsement `protobuf:"bytes,4,opt,name=endorsement,proto3" json:"endorsement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndorsementWrapper) Reset() {
	*x = EndorsementWrapper{}
	mi := &file_massa_model_v1_endorsement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndorsementWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndorsementWrapper) ProtoMessage() {}

func (x *EndorsementWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_endorsement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndorsementWrapper.ProtoReflect.Descriptor instead.
func (*EndorsementWrapper) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_endorsement_proto_rawDescGZIP(), []int{3}
}

func (x *EndorsementWrapper) GetInPool() bool {
	if x != nil {
		return x.InPool
	}
	return false
}

func (x *EndorsementWrapper) GetInBlocks() []string {
	if x != nil {
		return x.InBlocks
	}
	return nil
}

func (x *EndorsementWrapper) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *EndorsementWrapper) GetEndorsement() *SignedEndorsement {
	if x != nil {
		return x.Endorsement
	}
	return nil
}

// Informations about an endorsement with its metadata
type EndorsementInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The endorsement id
	EndorsementId string `protobuf:"bytes,1,opt,name=endorsement_id,json=endorsementId,proto3" json:"endorsement_id,omitempty"`
	// Whether the endorsement is still in pool
	InPool bool `protobuf:"varint,2,opt,name=in_pool,json=inPool,proto3" json:"in_pool,omitempty"`
	// The endorsement appears in `in_blocks`
	// If it appears in multiple blocks, these blocks are in different cliques
	InBlocks []string `protobuf:"bytes,3,rep,name=in_blocks,json=inBlocks,proto3" json:"in_blocks,omitempty"`
	// Whether the the endorsement is final (for example in a final block)
	IsFinal       bool `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndorsementInfo) Reset() {
	*x = EndorsementInfo{}
	mi := &file_massa_model_v1_endorsement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndorsementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndorsementInfo) ProtoMessage() {}

func (x *EndorsementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_endorsement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndorsementInfo.ProtoReflect.Descriptor instead.
func (*EndorsementInfo) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_endorsement_proto_rawDescGZIP(), []int{4}
}

func (x *EndorsementInfo) GetEndorsementId() string {
	if x != nil {
		return x.EndorsementId
	}
	return ""
}

func (x *EndorsementInfo) GetInPool() bool {
	if x != nil {
		return x.InPool
	}
	return false
}

func (x *EndorsementInfo) GetInBlocks() []string {
	if x != nil {
		return x.InBlocks
	}
	return nil
}

func (x *EndorsementInfo) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

var File_massa_model_v1_endorsement_proto protoreflect.FileDescriptor

const file_massa_model_v1_endorsement_proto_rawDesc = "" +
	"\n" +
	" massa/model/v1/endorsement.proto\x12\x0emassa.model.v1\x1a\x19massa/model/v1/slot.proto\"t\n" +
	"\vEndorsement\x12(\n" +
	"\x04slot\x18\x01 \x01(\v2\x14.massa.model.v1.SlotR\x04slot\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12%\n" +
	"\x0eendorsed_block\x18\x03 \x01(\tR\rendorsedBlock\"\xa1\x02\n" +
	"\x11SignedEndorsement\x125\n" +
	"\acontent\x18\x01 \x01(\v2\x1b.massa.model.v1.EndorsementR\acontent\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x125\n" +
	"\x17content_creator_pub_key\x18\x03 \x01(\tR\x14contentCreatorPubKey\x126\n" +
	"\x17content_creator_address\x18\x04 \x01(\tR\x15contentCreatorAddress\x12\x1f\n" +
	"\vsecure_hash\x18\x05 \x01(\tR\n" +
	"secureHash\x12'\n" +
	"\x0fserialized_size\x18\x06 \x01(\x04R\x0eserializedSize\"9\n" +
	"\x0eEndorsementIds\x12'\n" +
	"\x0fendorsement_ids\x18\x01 \x03(\tR\x0eendorsementIds\"\xaa\x01\n" +
	"\x12EndorsementWrapper\x12\x17\n" +
	"\ain_pool\x18\x01 \x01(\bR\x06inPool\x12\x1b\n" +
	"\tin_blocks\x18\x02 \x03(\tR\binBlocks\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\x12C\n" +
	"\vendorsement\x18\x04 \x01(\v2!.massa.model.v1.SignedEndorsementR\vendorsement\"\x89\x01\n" +
	"\x0fEndorsementInfo\x12%\n" +
	"\x0eendorsement_id\x18\x01 \x01(\tR\rendorsementId\x12\x17\n" +
	"\ain_pool\x18\x02 \x01(\bR\x06inPool\x12\x1b\n" +
	"\tin_blocks\x18\x03 \x03(\tR\binBlocks\x12\x19\n" +
	"\bis_final\x18\x04 \x01(\bR\aisFinalB\xa8\x01\n" +
	"\x12com.massa.model.v1P\x01Z<github.com/nafsilabs/massa-go/client/proto/massa/model/v1;v1\xa2\x02\x06MMODEL\xaa\x02\x12Com.Massa.Model.v1\xba\x02\x06MMODEL\xca\x02\x12Com\\Massa\\Model\\V1\xea\x02\x15Com::Massa::Model::V1b\x06proto3"

var (
	file_massa_model_v1_endorsement_proto_rawDescOnce sync.Once
	file_massa_model_v1_endorsement_proto_rawDescData []byte
)

func file_massa_model_v1_endorsement_proto_rawDescGZIP() []byte {
	file_massa_model_v1_endorsement_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_endorsement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_massa_model_v1_endorsement_proto_rawDesc), len(file_massa_model_v1_endorsement_proto_rawDesc)))
	})
	return file_massa_model_v1_endorsement_proto_rawDescData
}

var file_massa_model_v1_endorsement_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_massa_model_v1_endorsement_proto_goTypes = []any{
	(*Endorsement)(nil),        // 0: massa.model.v1.Endorsement
	(*SignedEndorsement)(nil),  // 1: massa.model.v1.SignedEndorsement
	(*EndorsementIds)(nil),     // 2: massa.model.v1.EndorsementIds
	(*EndorsementWrapper)(nil), // 3: massa.model.v1.EndorsementWrapper
	(*EndorsementInfo)(nil),    // 4: massa.model.v1.EndorsementInfo
	(*Slot)(nil),               // 5: massa.model.v1.Slot
}
var file_massa_model_v1_endorsement_proto_depIdxs = []int32{
	5, // 0: massa.model.v1.Endorsement.slot:type_name -> massa.model.v1.Slot
	0, // 1: massa.model.v1.SignedEndorsement.content:type_name -> massa.model.v1.Endorsement
	1, // 2: massa.model.v1.EndorsementWrapper.endorsement:type_name -> massa.model.v1.SignedEndorsement
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_massa_model_v1_endorsement_proto_init() }
func file_massa_model_v1_endorsement_proto_init() {
	if File_massa_model_v1_endorsement_proto != nil {
		return
	}
	file_massa_model_v1_slot_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_massa_model_v1_endorsement_proto_rawDesc), len(file_massa_model_v1_endorsement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_endorsement_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_endorsement_proto_depIdxs,
		MessageInfos:      file_massa_model_v1_endorsement_proto_msgTypes,
	}.Build()
	File_massa_model_v1_endorsement_proto = out.File
	file_massa_model_v1_endorsement_proto_goTypes = nil
	file_massa_model_v1_endorsement_proto_depIdxs = nil
}
