// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: massa/model/v1/operation.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operation type enum
type OpType int32

const (
	OpType_OP_TYPE_UNSPECIFIED OpType = 0 // Default enum value
	OpType_OP_TYPE_TRANSACTION OpType = 1 // Transaction
	OpType_OP_TYPE_ROLL_BUY    OpType = 2 // Roll buy
	OpType_OP_TYPE_ROLL_SELL   OpType = 3 // Roll sell
	OpType_OP_TYPE_EXECUTE_SC  OpType = 4 // Execute smart contract
	OpType_OP_TYPE_CALL_SC     OpType = 5 // Call smart contract
)

// Enum value maps for OpType.
var (
	OpType_name = map[int32]string{
		0: "OP_TYPE_UNSPECIFIED",
		1: "OP_TYPE_TRANSACTION",
		2: "OP_TYPE_ROLL_BUY",
		3: "OP_TYPE_ROLL_SELL",
		4: "OP_TYPE_EXECUTE_SC",
		5: "OP_TYPE_CALL_SC",
	}
	OpType_value = map[string]int32{
		"OP_TYPE_UNSPECIFIED": 0,
		"OP_TYPE_TRANSACTION": 1,
		"OP_TYPE_ROLL_BUY":    2,
		"OP_TYPE_ROLL_SELL":   3,
		"OP_TYPE_EXECUTE_SC":  4,
		"OP_TYPE_CALL_SC":     5,
	}
)

func (x OpType) Enum() *OpType {
	p := new(OpType)
	*p = x
	return p
}

func (x OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_massa_model_v1_operation_proto_enumTypes[0].Descriptor()
}

func (OpType) Type() protoreflect.EnumType {
	return &file_massa_model_v1_operation_proto_enumTypes[0]
}

func (x OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpType.Descriptor instead.
func (OpType) EnumDescriptor() ([]byte, []int) {
	return file_massa_model_v1_operation_proto_rawDescGZIP(), []int{0}
}

// The operation as sent in the network
type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The fee they have decided for this operation
	Fee *NativeAmount `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee,omitempty"`
	// After `expire_period` slot the operation won't be included in a block
	ExpirePeriod uint64 `protobuf:"varint,2,opt,name=expire_period,json=expirePeriod,proto3" json:"expire_period,omitempty"`
	// The type specific operation part
	Op            *OperationType `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_massa_model_v1_operation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_operation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_operation_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetFee() *NativeAmount {
	if x != nil {
		return x.Fee
	}
	return nil
}

func (x *Operation) GetExpirePeriod() uint64 {
	if x != nil {
		return x.ExpirePeriod
	}
	return 0
}

func (x *Operation) GetOp() *OperationType {
	if x != nil {
		return x.Op
	}
	return nil
}

// Type specific operation content
type OperationType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*OperationType_Transaction
	//	*OperationType_RollBuy
	//	*OperationType_RollSell
	//	*OperationType_ExecuteSc
	//	*OperationType_CallSc
	Type          isOperationType_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationType) Reset() {
	*x = OperationType{}
	mi := &file_massa_model_v1_operation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationType) ProtoMessage() {}

func (x *OperationType) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_operation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationType.ProtoReflect.Descriptor instead.
func (*OperationType) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_operation_proto_rawDescGZIP(), []int{1}
}

func (x *OperationType) GetType() isOperationType_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *OperationType) GetTransaction() *Transaction {
	if x != nil {
		if x, ok := x.Type.(*OperationType_Transaction); ok {
			return x.Transaction
		}
	}
	return nil
}

func (x *OperationType) GetRollBuy() *RollBuy {
	if x != nil {
		if x, ok := x.Type.(*OperationType_RollBuy); ok {
			return x.RollBuy
		}
	}
	return nil
}

func (x *OperationType) GetRollSell() *RollSell {
	if x != nil {
		if x, ok := x.Type.(*OperationType_RollSell); ok {
			return x.RollSell
		}
	}
	return nil
}

func (x *OperationType) GetExecuteSc() *ExecuteSC {
	if x != nil {
		if x, ok := x.Type.(*OperationType_ExecuteSc); ok {
			return x.ExecuteSc
		}
	}
	return nil
}

func (x *OperationType) GetCallSc() *CallSC {
	if x != nil {
		if x, ok := x.Type.(*OperationType_CallSc); ok {
			return x.CallSc
		}
	}
	return nil
}

type isOperationType_Type interface {
	isOperationType_Type()
}

type OperationType_Transaction struct {
	// Transfer coins from sender to recipient
	Transaction *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3,oneof"`
}

type OperationType_RollBuy struct {
	// The sender buys `roll_count` rolls. Roll price is defined in
	// configuration
	RollBuy *RollBuy `protobuf:"bytes,2,opt,name=roll_buy,json=rollBuy,proto3,oneof"`
}

type OperationType_RollSell struct {
	// The sender sells `roll_count` rolls. Roll price is defined in
	// configuration
	RollSell *RollSell `protobuf:"bytes,3,opt,name=roll_sell,json=rollSell,proto3,oneof"`
}

type OperationType_ExecuteSc struct {
	// Execute a smart contract
	ExecuteSc *ExecuteSC `protobuf:"bytes,4,opt,name=execute_sc,json=executeSc,proto3,oneof"`
}

type OperationType_CallSc struct {
	// Calls an exported function from a stored smart contract
	CallSc *CallSC `protobuf:"bytes,5,opt,name=call_sc,json=callSc,proto3,oneof"`
}

func (*OperationType_Transaction) isOperationType_Type() {}

func (*OperationType_RollBuy) isOperationType_Type() {}

func (*OperationType_RollSell) isOperationType_Type() {}

func (*OperationType_ExecuteSc) isOperationType_Type() {}

func (*OperationType_CallSc) isOperationType_Type() {}

// Transfer coins from sender to recipient
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recipient address
	RecipientAddress string `protobuf:"bytes,1,opt,name=recipient_address,json=recipientAddress,proto3" json:"recipient_address,omitempty"`
	// Amount
	Amount        *NativeAmount `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_massa_model_v1_operation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_operation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_operation_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetRecipientAddress() string {
	if x != nil {
		return x.RecipientAddress
	}
	return ""
}

func (x *Transaction) GetAmount() *NativeAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

// The sender buys `roll_count` rolls. Roll price is defined in configuration
type RollBuy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Roll count
	RollCount     uint64 `protobuf:"varint,1,opt,name=roll_count,json=rollCount,proto3" json:"roll_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollBuy) Reset() {
	*x = RollBuy{}
	mi := &file_massa_model_v1_operation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollBuy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollBuy) ProtoMessage() {}

func (x *RollBuy) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_operation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollBuy.ProtoReflect.Descriptor instead.
func (*RollBuy) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_operation_proto_rawDescGZIP(), []int{3}
}

func (x *RollBuy) GetRollCount() uint64 {
	if x != nil {
		return x.RollCount
	}
	return 0
}

// The sender sells `roll_count` rolls. Roll price is defined in configuration
type RollSell struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Roll count
	RollCount     uint64 `protobuf:"varint,1,opt,name=roll_count,json=rollCount,proto3" json:"roll_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollSell) Reset() {
	*x = RollSell{}
	mi := &file_massa_model_v1_operation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollSell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollSell) ProtoMessage() {}

func (x *RollSell) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_operation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollSell.ProtoReflect.Descriptor instead.
func (*RollSell) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_operation_proto_rawDescGZIP(), []int{4}
}

func (x *RollSell) GetRollCount() uint64 {
	if x != nil {
		return x.RollCount
	}
	return 0
}

// Execute a smart contract
type ExecuteSC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Smart contract bytecode.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The maximum of coins that could be spent by the operation sender
	MaxCoins uint64 `protobuf:"varint,2,opt,name=max_coins,json=maxCoins,proto3" json:"max_coins,omitempty"`
	// The maximum amount of gas that the execution of the contract is allowed to
	// cost
	MaxGas uint64 `protobuf:"varint,3,opt,name=max_gas,json=maxGas,proto3" json:"max_gas,omitempty"`
	// A key-value store associating a hash to arbitrary bytes
	Datastore     []*BytesMapFieldEntry `protobuf:"bytes,4,rep,name=datastore,proto3" json:"datastore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSC) Reset() {
	*x = ExecuteSC{}
	mi := &file_massa_model_v1_operation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSC) ProtoMessage() {}

func (x *ExecuteSC) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_operation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSC.ProtoReflect.Descriptor instead.
func (*ExecuteSC) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_operation_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteSC) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecuteSC) GetMaxCoins() uint64 {
	if x != nil {
		return x.MaxCoins
	}
	return 0
}

func (x *ExecuteSC) GetMaxGas() uint64 {
	if x != nil {
		return x.MaxGas
	}
	return 0
}

func (x *ExecuteSC) GetDatastore() []*BytesMapFieldEntry {
	if x != nil {
		return x.Datastore
	}
	return nil
}

// Calls an exported function from a stored smart contract
type CallSC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target smart contract address
	TargetAddress string `protobuf:"bytes,1,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	// Target function name. No function is called if empty
	TargetFunction string `protobuf:"bytes,2,opt,name=target_function,json=targetFunction,proto3" json:"target_function,omitempty"`
	// Parameter to pass to the target function
	Parameter []byte `protobuf:"bytes,3,opt,name=parameter,proto3" json:"parameter,omitempty"`
	// The maximum amount of gas that the execution of the contract is allowed to
	// cost
	MaxGas uint64 `protobuf:"varint,4,opt,name=max_gas,json=maxGas,proto3" json:"max_gas,omitempty"`
	// Extra coins that are spent from the caller's balance and transferred to the
	// target
	Coins         *NativeAmount `protobuf:"bytes,5,opt,name=coins,proto3" json:"coins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallSC) Reset() {
	*x = CallSC{}
	mi := &file_massa_model_v1_operation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallSC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallSC) ProtoMessage() {}

func (x *CallSC) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_operation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallSC.ProtoReflect.Descriptor instead.
func (*CallSC) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_operation_proto_rawDescGZIP(), []int{6}
}

func (x *CallSC) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *CallSC) GetTargetFunction() string {
	if x != nil {
		return x.TargetFunction
	}
	return ""
}

func (x *CallSC) GetParameter() []byte {
	if x != nil {
		return x.Parameter
	}
	return nil
}

func (x *CallSC) GetMaxGas() uint64 {
	if x != nil {
		return x.MaxGas
	}
	return 0
}

func (x *CallSC) GetCoins() *NativeAmount {
	if x != nil {
		return x.Coins
	}
	return nil
}

// Signed operation
type SignedOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation
	Content *Operation `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// A cryptographically generated value using `serialized_data` and a public
	// key.
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// The public-key component used in the generation of the signature
	ContentCreatorPubKey string `protobuf:"bytes,3,opt,name=content_creator_pub_key,json=contentCreatorPubKey,proto3" json:"content_creator_pub_key,omitempty"`
	// Derived from the same public key used to generate the signature
	ContentCreatorAddress string `protobuf:"bytes,4,opt,name=content_creator_address,json=contentCreatorAddress,proto3" json:"content_creator_address,omitempty"`
	// A secure hash of the non-malleable contents of a deterministic binary
	// representation of the block header
	SecureHash string `protobuf:"bytes,5,opt,name=secure_hash,json=secureHash,proto3" json:"secure_hash,omitempty"`
	// The size of the serialized operation in bytes
	SerializedSize uint64 `protobuf:"varint,6,opt,name=serialized_size,json=serializedSize,proto3" json:"serialized_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignedOperation) Reset() {
	*x = SignedOperation{}
	mi := &file_massa_model_v1_operation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedOperation) ProtoMessage() {}

func (x *SignedOperation) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_operation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedOperation.ProtoReflect.Descriptor instead.
func (*SignedOperation) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_operation_proto_rawDescGZIP(), []int{7}
}

func (x *SignedOperation) GetContent() *Operation {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SignedOperation) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignedOperation) GetContentCreatorPubKey() string {
	if x != nil {
		return x.ContentCreatorPubKey
	}
	return ""
}

func (x *SignedOperation) GetContentCreatorAddress() string {
	if x != nil {
		return x.ContentCreatorAddress
	}
	return ""
}

func (x *SignedOperation) GetSecureHash() string {
	if x != nil {
		return x.SecureHash
	}
	return ""
}

func (x *SignedOperation) GetSerializedSize() uint64 {
	if x != nil {
		return x.SerializedSize
	}
	return 0
}

// A wrapper around an operation with its metadata
type OperationWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The IDs of the blocks in which the operation appears
	BlockIds []string `protobuf:"bytes,1,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"`
	// The thread in which the operation can be included
	Thread uint32 `protobuf:"varint,2,opt,name=thread,proto3" json:"thread,omitempty"`
	// The operation object itself
	Operation     *SignedOperation `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationWrapper) Reset() {
	*x = OperationWrapper{}
	mi := &file_massa_model_v1_operation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationWrapper) ProtoMessage() {}

func (x *OperationWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_operation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationWrapper.ProtoReflect.Descriptor instead.
func (*OperationWrapper) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_operation_proto_rawDescGZIP(), []int{8}
}

func (x *OperationWrapper) GetBlockIds() []string {
	if x != nil {
		return x.BlockIds
	}
	return nil
}

func (x *OperationWrapper) GetThread() uint32 {
	if x != nil {
		return x.Thread
	}
	return 0
}

func (x *OperationWrapper) GetOperation() *SignedOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

// Information about an operation with its metadata
type OperationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the operation.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The IDs of the blocks in which the operation appears
	BlockIds []string `protobuf:"bytes,2,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"`
	// The thread in which the operation can be included
	Thread        uint32 `protobuf:"varint,3,opt,name=thread,proto3" json:"thread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationInfo) Reset() {
	*x = OperationInfo{}
	mi := &file_massa_model_v1_operation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationInfo) ProtoMessage() {}

func (x *OperationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_operation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationInfo.ProtoReflect.Descriptor instead.
func (*OperationInfo) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_operation_proto_rawDescGZIP(), []int{9}
}

func (x *OperationInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OperationInfo) GetBlockIds() []string {
	if x != nil {
		return x.BlockIds
	}
	return nil
}

func (x *OperationInfo) GetThread() uint32 {
	if x != nil {
		return x.Thread
	}
	return 0
}

// OperationIds
type OperationIds struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operations ids
	OperationIds  []string `protobuf:"bytes,1,rep,name=operation_ids,json=operationIds,proto3" json:"operation_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationIds) Reset() {
	*x = OperationIds{}
	mi := &file_massa_model_v1_operation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationIds) ProtoMessage() {}

func (x *OperationIds) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_operation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationIds.ProtoReflect.Descriptor instead.
func (*OperationIds) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_operation_proto_rawDescGZIP(), []int{10}
}

func (x *OperationIds) GetOperationIds() []string {
	if x != nil {
		return x.OperationIds
	}
	return nil
}

// OpTypes
type OpTypes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operations types
	OpTypes       []OpType `protobuf:"varint,1,rep,packed,name=op_types,json=opTypes,proto3,enum=massa.model.v1.OpType" json:"op_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpTypes) Reset() {
	*x = OpTypes{}
	mi := &file_massa_model_v1_operation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpTypes) ProtoMessage() {}

func (x *OpTypes) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_operation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpTypes.ProtoReflect.Descriptor instead.
func (*OpTypes) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_operation_proto_rawDescGZIP(), []int{11}
}

func (x *OpTypes) GetOpTypes() []OpType {
	if x != nil {
		return x.OpTypes
	}
	return nil
}

type OperationTypeRoll struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Address string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*OperationTypeRoll_RollBuy
	//	*OperationTypeRoll_RollSell
	Type          isOperationTypeRoll_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationTypeRoll) Reset() {
	*x = OperationTypeRoll{}
	mi := &file_massa_model_v1_operation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationTypeRoll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationTypeRoll) ProtoMessage() {}

func (x *OperationTypeRoll) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_operation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationTypeRoll.ProtoReflect.Descriptor instead.
func (*OperationTypeRoll) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_operation_proto_rawDescGZIP(), []int{12}
}

func (x *OperationTypeRoll) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OperationTypeRoll) GetType() isOperationTypeRoll_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *OperationTypeRoll) GetRollBuy() *RollBuy {
	if x != nil {
		if x, ok := x.Type.(*OperationTypeRoll_RollBuy); ok {
			return x.RollBuy
		}
	}
	return nil
}

func (x *OperationTypeRoll) GetRollSell() *RollSell {
	if x != nil {
		if x, ok := x.Type.(*OperationTypeRoll_RollSell); ok {
			return x.RollSell
		}
	}
	return nil
}

type isOperationTypeRoll_Type interface {
	isOperationTypeRoll_Type()
}

type OperationTypeRoll_RollBuy struct {
	RollBuy *RollBuy `protobuf:"bytes,2,opt,name=roll_buy,json=rollBuy,proto3,oneof"`
}

type OperationTypeRoll_RollSell struct {
	RollSell *RollSell `protobuf:"bytes,3,opt,name=roll_sell,json=rollSell,proto3,oneof"`
}

func (*OperationTypeRoll_RollBuy) isOperationTypeRoll_Type() {}

func (*OperationTypeRoll_RollSell) isOperationTypeRoll_Type() {}

var File_massa_model_v1_operation_proto protoreflect.FileDescriptor

const file_massa_model_v1_operation_proto_rawDesc = "" +
	"\n" +
	"\x1emassa/model/v1/operation.proto\x12\x0emassa.model.v1\x1a\x1bmassa/model/v1/amount.proto\x1a\x1cmassa/model/v1/commons.proto\"\x8f\x01\n" +
	"\tOperation\x12.\n" +
	"\x03fee\x18\x01 \x01(\v2\x1c.massa.model.v1.NativeAmountR\x03fee\x12#\n" +
	"\rexpire_period\x18\x02 \x01(\x04R\fexpirePeriod\x12-\n" +
	"\x02op\x18\x03 \x01(\v2\x1d.massa.model.v1.OperationTypeR\x02op\"\xb6\x02\n" +
	"\rOperationType\x12?\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1b.massa.model.v1.TransactionH\x00R\vtransaction\x124\n" +
	"\broll_buy\x18\x02 \x01(\v2\x17.massa.model.v1.RollBuyH\x00R\arollBuy\x127\n" +
	"\troll_sell\x18\x03 \x01(\v2\x18.massa.model.v1.RollSellH\x00R\brollSell\x12:\n" +
	"\n" +
	"execute_sc\x18\x04 \x01(\v2\x19.massa.model.v1.ExecuteSCH\x00R\texecuteSc\x121\n" +
	"\acall_sc\x18\x05 \x01(\v2\x16.massa.model.v1.CallSCH\x00R\x06callScB\x06\n" +
	"\x04type\"p\n" +
	"\vTransaction\x12+\n" +
	"\x11recipient_address\x18\x01 \x01(\tR\x10recipientAddress\x124\n" +
	"\x06amount\x18\x02 \x01(\v2\x1c.massa.model.v1.NativeAmountR\x06amount\"(\n" +
	"\aRollBuy\x12\x1d\n" +
	"\n" +
	"roll_count\x18\x01 \x01(\x04R\trollCount\")\n" +
	"\bRollSell\x12\x1d\n" +
	"\n" +
	"roll_count\x18\x01 \x01(\x04R\trollCount\"\x97\x01\n" +
	"\tExecuteSC\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tmax_coins\x18\x02 \x01(\x04R\bmaxCoins\x12\x17\n" +
	"\amax_gas\x18\x03 \x01(\x04R\x06maxGas\x12@\n" +
	"\tdatastore\x18\x04 \x03(\v2\".massa.model.v1.BytesMapFieldEntryR\tdatastore\"\xc3\x01\n" +
	"\x06CallSC\x12%\n" +
	"\x0etarget_address\x18\x01 \x01(\tR\rtargetAddress\x12'\n" +
	"\x0ftarget_function\x18\x02 \x01(\tR\x0etargetFunction\x12\x1c\n" +
	"\tparameter\x18\x03 \x01(\fR\tparameter\x12\x17\n" +
	"\amax_gas\x18\x04 \x01(\x04R\x06maxGas\x122\n" +
	"\x05coins\x18\x05 \x01(\v2\x1c.massa.model.v1.NativeAmountR\x05coins\"\x9d\x02\n" +
	"\x0fSignedOperation\x123\n" +
	"\acontent\x18\x01 \x01(\v2\x19.massa.model.v1.OperationR\acontent\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x125\n" +
	"\x17content_creator_pub_key\x18\x03 \x01(\tR\x14contentCreatorPubKey\x126\n" +
	"\x17content_creator_address\x18\x04 \x01(\tR\x15contentCreatorAddress\x12\x1f\n" +
	"\vsecure_hash\x18\x05 \x01(\tR\n" +
	"secureHash\x12'\n" +
	"\x0fserialized_size\x18\x06 \x01(\x04R\x0eserializedSize\"\x86\x01\n" +
	"\x10OperationWrapper\x12\x1b\n" +
	"\tblock_ids\x18\x01 \x03(\tR\bblockIds\x12\x16\n" +
	"\x06thread\x18\x02 \x01(\rR\x06thread\x12=\n" +
	"\toperation\x18\x03 \x01(\v2\x1f.massa.model.v1.SignedOperationR\toperation\"T\n" +
	"\rOperationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tblock_ids\x18\x02 \x03(\tR\bblockIds\x12\x16\n" +
	"\x06thread\x18\x03 \x01(\rR\x06thread\"3\n" +
	"\fOperationIds\x12#\n" +
	"\roperation_ids\x18\x01 \x03(\tR\foperationIds\"<\n" +
	"\aOpTypes\x121\n" +
	"\bop_types\x18\x01 \x03(\x0e2\x16.massa.model.v1.OpTypeR\aopTypes\"\xa4\x01\n" +
	"\x11OperationTypeRoll\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x124\n" +
	"\broll_buy\x18\x02 \x01(\v2\x17.massa.model.v1.RollBuyH\x00R\arollBuy\x127\n" +
	"\troll_sell\x18\x03 \x01(\v2\x18.massa.model.v1.RollSellH\x00R\brollSellB\x06\n" +
	"\x04type*\x94\x01\n" +
	"\x06OpType\x12\x17\n" +
	"\x13OP_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13OP_TYPE_TRANSACTION\x10\x01\x12\x14\n" +
	"\x10OP_TYPE_ROLL_BUY\x10\x02\x12\x15\n" +
	"\x11OP_TYPE_ROLL_SELL\x10\x03\x12\x16\n" +
	"\x12OP_TYPE_EXECUTE_SC\x10\x04\x12\x13\n" +
	"\x0fOP_TYPE_CALL_SC\x10\x05B\xa8\x01\n" +
	"\x12com.massa.model.v1P\x01Z<github.com/nafsilabs/massa-go/client/proto/massa/model/v1;v1\xa2\x02\x06MMODEL\xaa\x02\x12Com.Massa.Model.v1\xba\x02\x06MMODEL\xca\x02\x12Com\\Massa\\Model\\V1\xea\x02\x15Com::Massa::Model::V1b\x06proto3"

var (
	file_massa_model_v1_operation_proto_rawDescOnce sync.Once
	file_massa_model_v1_operation_proto_rawDescData []byte
)

func file_massa_model_v1_operation_proto_rawDescGZIP() []byte {
	file_massa_model_v1_operation_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_operation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_massa_model_v1_operation_proto_rawDesc), len(file_massa_model_v1_operation_proto_rawDesc)))
	})
	return file_massa_model_v1_operation_proto_rawDescData
}

var file_massa_model_v1_operation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_massa_model_v1_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_massa_model_v1_operation_proto_goTypes = []any{
	(OpType)(0),                // 0: massa.model.v1.OpType
	(*Operation)(nil),          // 1: massa.model.v1.Operation
	(*OperationType)(nil),      // 2: massa.model.v1.OperationType
	(*Transaction)(nil),        // 3: massa.model.v1.Transaction
	(*RollBuy)(nil),            // 4: massa.model.v1.RollBuy
	(*RollSell)(nil),           // 5: massa.model.v1.RollSell
	(*ExecuteSC)(nil),          // 6: massa.model.v1.ExecuteSC
	(*CallSC)(nil),             // 7: massa.model.v1.CallSC
	(*SignedOperation)(nil),    // 8: massa.model.v1.SignedOperation
	(*OperationWrapper)(nil),   // 9: massa.model.v1.OperationWrapper
	(*OperationInfo)(nil),      // 10: massa.model.v1.OperationInfo
	(*OperationIds)(nil),       // 11: massa.model.v1.OperationIds
	(*OpTypes)(nil),            // 12: massa.model.v1.OpTypes
	(*OperationTypeRoll)(nil),  // 13: massa.model.v1.OperationTypeRoll
	(*NativeAmount)(nil),       // 14: massa.model.v1.NativeAmount
	(*BytesMapFieldEntry)(nil), // 15: massa.model.v1.BytesMapFieldEntry
}
var file_massa_model_v1_operation_proto_depIdxs = []int32{
	14, // 0: massa.model.v1.Operation.fee:type_name -> massa.model.v1.NativeAmount
	2,  // 1: massa.model.v1.Operation.op:type_name -> massa.model.v1.OperationType
	3,  // 2: massa.model.v1.OperationType.transaction:type_name -> massa.model.v1.Transaction
	4,  // 3: massa.model.v1.OperationType.roll_buy:type_name -> massa.model.v1.RollBuy
	5,  // 4: massa.model.v1.OperationType.roll_sell:type_name -> massa.model.v1.RollSell
	6,  // 5: massa.model.v1.OperationType.execute_sc:type_name -> massa.model.v1.ExecuteSC
	7,  // 6: massa.model.v1.OperationType.call_sc:type_name -> massa.model.v1.CallSC
	14, // 7: massa.model.v1.Transaction.amount:type_name -> massa.model.v1.NativeAmount
	15, // 8: massa.model.v1.ExecuteSC.datastore:type_name -> massa.model.v1.BytesMapFieldEntry
	14, // 9: massa.model.v1.CallSC.coins:type_name -> massa.model.v1.NativeAmount
	1,  // 10: massa.model.v1.SignedOperation.content:type_name -> massa.model.v1.Operation
	8,  // 11: massa.model.v1.OperationWrapper.operation:type_name -> massa.model.v1.SignedOperation
	0,  // 12: massa.model.v1.OpTypes.op_types:type_name -> massa.model.v1.OpType
	4,  // 13: massa.model.v1.OperationTypeRoll.roll_buy:type_name -> massa.model.v1.RollBuy
	5,  // 14: massa.model.v1.OperationTypeRoll.roll_sell:type_name -> massa.model.v1.RollSell
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_massa_model_v1_operation_proto_init() }
func file_massa_model_v1_operation_proto_init() {
	if File_massa_model_v1_operation_proto != nil {
		return
	}
	file_massa_model_v1_amount_proto_init()
	file_massa_model_v1_commons_proto_init()
	file_massa_model_v1_operation_proto_msgTypes[1].OneofWrappers = []any{
		(*OperationType_Transaction)(nil),
		(*OperationType_RollBuy)(nil),
		(*OperationType_RollSell)(nil),
		(*OperationType_ExecuteSc)(nil),
		(*OperationType_CallSc)(nil),
	}
	file_massa_model_v1_operation_proto_msgTypes[12].OneofWrappers = []any{
		(*OperationTypeRoll_RollBuy)(nil),
		(*OperationTypeRoll_RollSell)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_massa_model_v1_operation_proto_rawDesc), len(file_massa_model_v1_operation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_operation_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_operation_proto_depIdxs,
		EnumInfos:         file_massa_model_v1_operation_proto_enumTypes,
		MessageInfos:      file_massa_model_v1_operation_proto_msgTypes,
	}.Build()
	File_massa_model_v1_operation_proto = out.File
	file_massa_model_v1_operation_proto_goTypes = nil
	file_massa_model_v1_operation_proto_depIdxs = nil
}
