// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: massa/model/v1/slot.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// When an address is drawn to create an endorsement it is selected for a specific index
type IndexedSlot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Slot
	Slot *Slot `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// Endorsement index in the slot
	Index         uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexedSlot) Reset() {
	*x = IndexedSlot{}
	mi := &file_massa_model_v1_slot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexedSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexedSlot) ProtoMessage() {}

func (x *IndexedSlot) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_slot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexedSlot.ProtoReflect.Descriptor instead.
func (*IndexedSlot) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_slot_proto_rawDescGZIP(), []int{0}
}

func (x *IndexedSlot) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *IndexedSlot) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

// A point in time where a block is expected
type Slot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Period
	Period uint64 `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`
	// Thread
	Thread        uint32 `protobuf:"varint,2,opt,name=thread,proto3" json:"thread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slot) Reset() {
	*x = Slot{}
	mi := &file_massa_model_v1_slot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_slot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_slot_proto_rawDescGZIP(), []int{1}
}

func (x *Slot) GetPeriod() uint64 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *Slot) GetThread() uint32 {
	if x != nil {
		return x.Thread
	}
	return 0
}

// Slots
type Slots struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Slots
	Slots         []*Slot `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slots) Reset() {
	*x = Slots{}
	mi := &file_massa_model_v1_slot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slots) ProtoMessage() {}

func (x *Slots) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_slot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slots.ProtoReflect.Descriptor instead.
func (*Slots) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_slot_proto_rawDescGZIP(), []int{2}
}

func (x *Slots) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

// SlotRange
type SlotRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start lot (Optional)
	StartSlot *Slot `protobuf:"bytes,1,opt,name=start_slot,json=startSlot,proto3" json:"start_slot,omitempty"`
	// End slot (Optional)
	EndSlot       *Slot `protobuf:"bytes,2,opt,name=end_slot,json=endSlot,proto3" json:"end_slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotRange) Reset() {
	*x = SlotRange{}
	mi := &file_massa_model_v1_slot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotRange) ProtoMessage() {}

func (x *SlotRange) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_slot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotRange.ProtoReflect.Descriptor instead.
func (*SlotRange) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_slot_proto_rawDescGZIP(), []int{3}
}

func (x *SlotRange) GetStartSlot() *Slot {
	if x != nil {
		return x.StartSlot
	}
	return nil
}

func (x *SlotRange) GetEndSlot() *Slot {
	if x != nil {
		return x.EndSlot
	}
	return nil
}

var File_massa_model_v1_slot_proto protoreflect.FileDescriptor

const file_massa_model_v1_slot_proto_rawDesc = "" +
	"\n" +
	"\x19massa/model/v1/slot.proto\x12\x0emassa.model.v1\"M\n" +
	"\vIndexedSlot\x12(\n" +
	"\x04slot\x18\x01 \x01(\v2\x14.massa.model.v1.SlotR\x04slot\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\"6\n" +
	"\x04Slot\x12\x16\n" +
	"\x06period\x18\x01 \x01(\x04R\x06period\x12\x16\n" +
	"\x06thread\x18\x02 \x01(\rR\x06thread\"3\n" +
	"\x05Slots\x12*\n" +
	"\x05slots\x18\x01 \x03(\v2\x14.massa.model.v1.SlotR\x05slots\"q\n" +
	"\tSlotRange\x123\n" +
	"\n" +
	"start_slot\x18\x01 \x01(\v2\x14.massa.model.v1.SlotR\tstartSlot\x12/\n" +
	"\bend_slot\x18\x02 \x01(\v2\x14.massa.model.v1.SlotR\aendSlotB\xa8\x01\n" +
	"\x12com.massa.model.v1P\x01Z<github.com/nafsilabs/massa-go/client/proto/massa/model/v1;v1\xa2\x02\x06MMODEL\xaa\x02\x12Com.Massa.Model.v1\xba\x02\x06MMODEL\xca\x02\x12Com\\Massa\\Model\\V1\xea\x02\x15Com::Massa::Model::V1b\x06proto3"

var (
	file_massa_model_v1_slot_proto_rawDescOnce sync.Once
	file_massa_model_v1_slot_proto_rawDescData []byte
)

func file_massa_model_v1_slot_proto_rawDescGZIP() []byte {
	file_massa_model_v1_slot_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_slot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_massa_model_v1_slot_proto_rawDesc), len(file_massa_model_v1_slot_proto_rawDesc)))
	})
	return file_massa_model_v1_slot_proto_rawDescData
}

var file_massa_model_v1_slot_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_massa_model_v1_slot_proto_goTypes = []any{
	(*IndexedSlot)(nil), // 0: massa.model.v1.IndexedSlot
	(*Slot)(nil),        // 1: massa.model.v1.Slot
	(*Slots)(nil),       // 2: massa.model.v1.Slots
	(*SlotRange)(nil),   // 3: massa.model.v1.SlotRange
}
var file_massa_model_v1_slot_proto_depIdxs = []int32{
	1, // 0: massa.model.v1.IndexedSlot.slot:type_name -> massa.model.v1.Slot
	1, // 1: massa.model.v1.Slots.slots:type_name -> massa.model.v1.Slot
	1, // 2: massa.model.v1.SlotRange.start_slot:type_name -> massa.model.v1.Slot
	1, // 3: massa.model.v1.SlotRange.end_slot:type_name -> massa.model.v1.Slot
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_massa_model_v1_slot_proto_init() }
func file_massa_model_v1_slot_proto_init() {
	if File_massa_model_v1_slot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_massa_model_v1_slot_proto_rawDesc), len(file_massa_model_v1_slot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_slot_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_slot_proto_depIdxs,
		MessageInfos:      file_massa_model_v1_slot_proto_msgTypes,
	}.Build()
	File_massa_model_v1_slot_proto = out.File
	file_massa_model_v1_slot_proto_goTypes = nil
	file_massa_model_v1_slot_proto_depIdxs = nil
}
