// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: massa/model/v1/stats.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Consensus statistics
type ConsensusStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start of the time span for stats
	StartTimespan *NativeTime `protobuf:"bytes,1,opt,name=start_timespan,json=startTimespan,proto3" json:"start_timespan,omitempty"`
	// End of the time span for stats
	EndTimespan *NativeTime `protobuf:"bytes,2,opt,name=end_timespan,json=endTimespan,proto3" json:"end_timespan,omitempty"`
	// Number of final blocks
	FinalBlockCount uint64 `protobuf:"varint,3,opt,name=final_block_count,json=finalBlockCount,proto3" json:"final_block_count,omitempty"`
	// Number of stale blocks in memory
	StaleBlockCount uint64 `protobuf:"varint,4,opt,name=stale_block_count,json=staleBlockCount,proto3" json:"stale_block_count,omitempty"`
	// Number of actives cliques
	CliqueCount   uint64 `protobuf:"varint,5,opt,name=clique_count,json=cliqueCount,proto3" json:"clique_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusStats) Reset() {
	*x = ConsensusStats{}
	mi := &file_massa_model_v1_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusStats) ProtoMessage() {}

func (x *ConsensusStats) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusStats.ProtoReflect.Descriptor instead.
func (*ConsensusStats) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_stats_proto_rawDescGZIP(), []int{0}
}

func (x *ConsensusStats) GetStartTimespan() *NativeTime {
	if x != nil {
		return x.StartTimespan
	}
	return nil
}

func (x *ConsensusStats) GetEndTimespan() *NativeTime {
	if x != nil {
		return x.EndTimespan
	}
	return nil
}

func (x *ConsensusStats) GetFinalBlockCount() uint64 {
	if x != nil {
		return x.FinalBlockCount
	}
	return 0
}

func (x *ConsensusStats) GetStaleBlockCount() uint64 {
	if x != nil {
		return x.StaleBlockCount
	}
	return 0
}

func (x *ConsensusStats) GetCliqueCount() uint64 {
	if x != nil {
		return x.CliqueCount
	}
	return 0
}

// Pool statistics
type PoolStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endorsements
	EndorsementsCount uint64 `protobuf:"varint,1,opt,name=endorsements_count,json=endorsementsCount,proto3" json:"endorsements_count,omitempty"`
	// Operations
	OperationsCount uint64 `protobuf:"varint,2,opt,name=operations_count,json=operationsCount,proto3" json:"operations_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PoolStats) Reset() {
	*x = PoolStats{}
	mi := &file_massa_model_v1_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolStats) ProtoMessage() {}

func (x *PoolStats) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolStats.ProtoReflect.Descriptor instead.
func (*PoolStats) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_stats_proto_rawDescGZIP(), []int{1}
}

func (x *PoolStats) GetEndorsementsCount() uint64 {
	if x != nil {
		return x.EndorsementsCount
	}
	return 0
}

func (x *PoolStats) GetOperationsCount() uint64 {
	if x != nil {
		return x.OperationsCount
	}
	return 0
}

// Network statistics
type NetworkStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// In connections count
	InConnectionCount uint64 `protobuf:"varint,1,opt,name=in_connection_count,json=inConnectionCount,proto3" json:"in_connection_count,omitempty"`
	// Out connections count
	OutConnectionCount uint64 `protobuf:"varint,2,opt,name=out_connection_count,json=outConnectionCount,proto3" json:"out_connection_count,omitempty"`
	// Total known peers count
	KnownPeerCount uint64 `protobuf:"varint,3,opt,name=known_peer_count,json=knownPeerCount,proto3" json:"known_peer_count,omitempty"`
	// Banned node count
	BannedPeerCount uint64 `protobuf:"varint,4,opt,name=banned_peer_count,json=bannedPeerCount,proto3" json:"banned_peer_count,omitempty"`
	// Active node count
	ActiveNodeCount uint64 `protobuf:"varint,5,opt,name=active_node_count,json=activeNodeCount,proto3" json:"active_node_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NetworkStats) Reset() {
	*x = NetworkStats{}
	mi := &file_massa_model_v1_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStats) ProtoMessage() {}

func (x *NetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStats.ProtoReflect.Descriptor instead.
func (*NetworkStats) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_stats_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkStats) GetInConnectionCount() uint64 {
	if x != nil {
		return x.InConnectionCount
	}
	return 0
}

func (x *NetworkStats) GetOutConnectionCount() uint64 {
	if x != nil {
		return x.OutConnectionCount
	}
	return 0
}

func (x *NetworkStats) GetKnownPeerCount() uint64 {
	if x != nil {
		return x.KnownPeerCount
	}
	return 0
}

func (x *NetworkStats) GetBannedPeerCount() uint64 {
	if x != nil {
		return x.BannedPeerCount
	}
	return 0
}

func (x *NetworkStats) GetActiveNodeCount() uint64 {
	if x != nil {
		return x.ActiveNodeCount
	}
	return 0
}

// Execution statistics
type ExecutionStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time window start
	TimeWindowStart *NativeTime `protobuf:"bytes,1,opt,name=time_window_start,json=timeWindowStart,proto3" json:"time_window_start,omitempty"`
	// Time window end
	TimeWindowEnd *NativeTime `protobuf:"bytes,2,opt,name=time_window_end,json=timeWindowEnd,proto3" json:"time_window_end,omitempty"`
	// Number of final blocks in the time window
	FinalBlockCount uint64 `protobuf:"varint,3,opt,name=final_block_count,json=finalBlockCount,proto3" json:"final_block_count,omitempty"`
	// Number of final executed operations in the time window
	FinalExecutedOperationsCount uint64 `protobuf:"varint,4,opt,name=final_executed_operations_count,json=finalExecutedOperationsCount,proto3" json:"final_executed_operations_count,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ExecutionStats) Reset() {
	*x = ExecutionStats{}
	mi := &file_massa_model_v1_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionStats) ProtoMessage() {}

func (x *ExecutionStats) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionStats.ProtoReflect.Descriptor instead.
func (*ExecutionStats) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_stats_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutionStats) GetTimeWindowStart() *NativeTime {
	if x != nil {
		return x.TimeWindowStart
	}
	return nil
}

func (x *ExecutionStats) GetTimeWindowEnd() *NativeTime {
	if x != nil {
		return x.TimeWindowEnd
	}
	return nil
}

func (x *ExecutionStats) GetFinalBlockCount() uint64 {
	if x != nil {
		return x.FinalBlockCount
	}
	return 0
}

func (x *ExecutionStats) GetFinalExecutedOperationsCount() uint64 {
	if x != nil {
		return x.FinalExecutedOperationsCount
	}
	return 0
}

var File_massa_model_v1_stats_proto protoreflect.FileDescriptor

const file_massa_model_v1_stats_proto_rawDesc = "" +
	"\n" +
	"\x1amassa/model/v1/stats.proto\x12\x0emassa.model.v1\x1a\x19massa/model/v1/time.proto\"\x8d\x02\n" +
	"\x0eConsensusStats\x12A\n" +
	"\x0estart_timespan\x18\x01 \x01(\v2\x1a.massa.model.v1.NativeTimeR\rstartTimespan\x12=\n" +
	"\fend_timespan\x18\x02 \x01(\v2\x1a.massa.model.v1.NativeTimeR\vendTimespan\x12*\n" +
	"\x11final_block_count\x18\x03 \x01(\x04R\x0ffinalBlockCount\x12*\n" +
	"\x11stale_block_count\x18\x04 \x01(\x04R\x0fstaleBlockCount\x12!\n" +
	"\fclique_count\x18\x05 \x01(\x04R\vcliqueCount\"e\n" +
	"\tPoolStats\x12-\n" +
	"\x12endorsements_count\x18\x01 \x01(\x04R\x11endorsementsCount\x12)\n" +
	"\x10operations_count\x18\x02 \x01(\x04R\x0foperationsCount\"\xf2\x01\n" +
	"\fNetworkStats\x12.\n" +
	"\x13in_connection_count\x18\x01 \x01(\x04R\x11inConnectionCount\x120\n" +
	"\x14out_connection_count\x18\x02 \x01(\x04R\x12outConnectionCount\x12(\n" +
	"\x10known_peer_count\x18\x03 \x01(\x04R\x0eknownPeerCount\x12*\n" +
	"\x11banned_peer_count\x18\x04 \x01(\x04R\x0fbannedPeerCount\x12*\n" +
	"\x11active_node_count\x18\x05 \x01(\x04R\x0factiveNodeCount\"\x8f\x02\n" +
	"\x0eExecutionStats\x12F\n" +
	"\x11time_window_start\x18\x01 \x01(\v2\x1a.massa.model.v1.NativeTimeR\x0ftimeWindowStart\x12B\n" +
	"\x0ftime_window_end\x18\x02 \x01(\v2\x1a.massa.model.v1.NativeTimeR\rtimeWindowEnd\x12*\n" +
	"\x11final_block_count\x18\x03 \x01(\x04R\x0ffinalBlockCount\x12E\n" +
	"\x1ffinal_executed_operations_count\x18\x04 \x01(\x04R\x1cfinalExecutedOperationsCountB\xa8\x01\n" +
	"\x12com.massa.model.v1P\x01Z<github.com/nafsilabs/massa-go/client/proto/massa/model/v1;v1\xa2\x02\x06MMODEL\xaa\x02\x12Com.Massa.Model.v1\xba\x02\x06MMODEL\xca\x02\x12Com\\Massa\\Model\\V1\xea\x02\x15Com::Massa::Model::V1b\x06proto3"

var (
	file_massa_model_v1_stats_proto_rawDescOnce sync.Once
	file_massa_model_v1_stats_proto_rawDescData []byte
)

func file_massa_model_v1_stats_proto_rawDescGZIP() []byte {
	file_massa_model_v1_stats_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_massa_model_v1_stats_proto_rawDesc), len(file_massa_model_v1_stats_proto_rawDesc)))
	})
	return file_massa_model_v1_stats_proto_rawDescData
}

var file_massa_model_v1_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_massa_model_v1_stats_proto_goTypes = []any{
	(*ConsensusStats)(nil), // 0: massa.model.v1.ConsensusStats
	(*PoolStats)(nil),      // 1: massa.model.v1.PoolStats
	(*NetworkStats)(nil),   // 2: massa.model.v1.NetworkStats
	(*ExecutionStats)(nil), // 3: massa.model.v1.ExecutionStats
	(*NativeTime)(nil),     // 4: massa.model.v1.NativeTime
}
var file_massa_model_v1_stats_proto_depIdxs = []int32{
	4, // 0: massa.model.v1.ConsensusStats.start_timespan:type_name -> massa.model.v1.NativeTime
	4, // 1: massa.model.v1.ConsensusStats.end_timespan:type_name -> massa.model.v1.NativeTime
	4, // 2: massa.model.v1.ExecutionStats.time_window_start:type_name -> massa.model.v1.NativeTime
	4, // 3: massa.model.v1.ExecutionStats.time_window_end:type_name -> massa.model.v1.NativeTime
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_massa_model_v1_stats_proto_init() }
func file_massa_model_v1_stats_proto_init() {
	if File_massa_model_v1_stats_proto != nil {
		return
	}
	file_massa_model_v1_time_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_massa_model_v1_stats_proto_rawDesc), len(file_massa_model_v1_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_stats_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_stats_proto_depIdxs,
		MessageInfos:      file_massa_model_v1_stats_proto_msgTypes,
	}.Build()
	File_massa_model_v1_stats_proto = out.File
	file_massa_model_v1_stats_proto_goTypes = nil
	file_massa_model_v1_stats_proto_depIdxs = nil
}
