// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: massa/model/v1/versioning.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State machine for a Versioning component that tracks the deployment state
type ComponentStateId int32

const (
	ComponentStateId_COMPONENT_STATE_ID_UNSPECIFIED ComponentStateId = 0 // Default enum value
	ComponentStateId_COMPONENT_STATE_ID_ERROR       ComponentStateId = 1 // Error state
	ComponentStateId_COMPONENT_STATE_ID_DEFINED     ComponentStateId = 2 // Initial state
	ComponentStateId_COMPONENT_STATE_ID_STARTED     ComponentStateId = 3 // Past start, can only go to LockedIn after the threshold is above a given value
	ComponentStateId_COMPONENT_STATE_ID_LOCKEDIN    ComponentStateId = 4 // Locked but wait for some time before going to active (to let users the time to upgrade)
	ComponentStateId_COMPONENT_STATE_ID_ACTIVE      ComponentStateId = 5 // After LockedIn, deployment is considered successful (after activation delay)
	ComponentStateId_COMPONENT_STATE_ID_FAILED      ComponentStateId = 6 // Past the timeout, if LockedIn is not reach
)

// Enum value maps for ComponentStateId.
var (
	ComponentStateId_name = map[int32]string{
		0: "COMPONENT_STATE_ID_UNSPECIFIED",
		1: "COMPONENT_STATE_ID_ERROR",
		2: "COMPONENT_STATE_ID_DEFINED",
		3: "COMPONENT_STATE_ID_STARTED",
		4: "COMPONENT_STATE_ID_LOCKEDIN",
		5: "COMPONENT_STATE_ID_ACTIVE",
		6: "COMPONENT_STATE_ID_FAILED",
	}
	ComponentStateId_value = map[string]int32{
		"COMPONENT_STATE_ID_UNSPECIFIED": 0,
		"COMPONENT_STATE_ID_ERROR":       1,
		"COMPONENT_STATE_ID_DEFINED":     2,
		"COMPONENT_STATE_ID_STARTED":     3,
		"COMPONENT_STATE_ID_LOCKEDIN":    4,
		"COMPONENT_STATE_ID_ACTIVE":      5,
		"COMPONENT_STATE_ID_FAILED":      6,
	}
)

func (x ComponentStateId) Enum() *ComponentStateId {
	p := new(ComponentStateId)
	*p = x
	return p
}

func (x ComponentStateId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentStateId) Descriptor() protoreflect.EnumDescriptor {
	return file_massa_model_v1_versioning_proto_enumTypes[0].Descriptor()
}

func (ComponentStateId) Type() protoreflect.EnumType {
	return &file_massa_model_v1_versioning_proto_enumTypes[0]
}

func (x ComponentStateId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentStateId.Descriptor instead.
func (ComponentStateId) EnumDescriptor() ([]byte, []int) {
	return file_massa_model_v1_versioning_proto_rawDescGZIP(), []int{0}
}

// Versioning component enum
type MipComponent int32

const (
	MipComponent_MIP_COMPONENT_UNSPECIFIED MipComponent = 0 // Default enum value
	MipComponent_MIP_COMPONENT_ADDRESS     MipComponent = 1 // Address component
	MipComponent_MIP_COMPONENT_KEYPAIR     MipComponent = 2 // Keypair component
)

// Enum value maps for MipComponent.
var (
	MipComponent_name = map[int32]string{
		0: "MIP_COMPONENT_UNSPECIFIED",
		1: "MIP_COMPONENT_ADDRESS",
		2: "MIP_COMPONENT_KEYPAIR",
	}
	MipComponent_value = map[string]int32{
		"MIP_COMPONENT_UNSPECIFIED": 0,
		"MIP_COMPONENT_ADDRESS":     1,
		"MIP_COMPONENT_KEYPAIR":     2,
	}
)

func (x MipComponent) Enum() *MipComponent {
	p := new(MipComponent)
	*p = x
	return p
}

func (x MipComponent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MipComponent) Descriptor() protoreflect.EnumDescriptor {
	return file_massa_model_v1_versioning_proto_enumTypes[1].Descriptor()
}

func (MipComponent) Type() protoreflect.EnumType {
	return &file_massa_model_v1_versioning_proto_enumTypes[1]
}

func (x MipComponent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MipComponent.Descriptor instead.
func (MipComponent) EnumDescriptor() ([]byte, []int) {
	return file_massa_model_v1_versioning_proto_rawDescGZIP(), []int{1}
}

// Entry for GetMipStatusResponse
type MipStatusEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mip info
	MipInfo *MipInfo `protobuf:"bytes,1,opt,name=mip_info,json=mipInfo,proto3" json:"mip_info,omitempty"`
	// State id
	StateId       ComponentStateId `protobuf:"varint,2,opt,name=state_id,json=stateId,proto3,enum=massa.model.v1.ComponentStateId" json:"state_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MipStatusEntry) Reset() {
	*x = MipStatusEntry{}
	mi := &file_massa_model_v1_versioning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MipStatusEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MipStatusEntry) ProtoMessage() {}

func (x *MipStatusEntry) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_versioning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MipStatusEntry.ProtoReflect.Descriptor instead.
func (*MipStatusEntry) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_versioning_proto_rawDescGZIP(), []int{0}
}

func (x *MipStatusEntry) GetMipInfo() *MipInfo {
	if x != nil {
		return x.MipInfo
	}
	return nil
}

func (x *MipStatusEntry) GetStateId() ComponentStateId {
	if x != nil {
		return x.StateId
	}
	return ComponentStateId_COMPONENT_STATE_ID_UNSPECIFIED
}

// MIP info (name & versions & time range for a MIP)
type MipInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MIP name or descriptive name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Network (or global) version (to be included in block header)
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// A timestamp at which the version gains its meaning (e.g. announced in block header)
	Start *NativeTime `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	// A timestamp at the which the deployment is considered failed
	Timeout *NativeTime `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Once deployment has been locked, wait for this duration before deployment is considered active
	ActivationDelay *NativeTime `protobuf:"bytes,5,opt,name=activation_delay,json=activationDelay,proto3" json:"activation_delay,omitempty"`
	// Components concerned by this versioning (e.g. a new Block version), and the associated component_version
	Components    []*MipComponentEntry `protobuf:"bytes,6,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MipInfo) Reset() {
	*x = MipInfo{}
	mi := &file_massa_model_v1_versioning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MipInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MipInfo) ProtoMessage() {}

func (x *MipInfo) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_versioning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MipInfo.ProtoReflect.Descriptor instead.
func (*MipInfo) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_versioning_proto_rawDescGZIP(), []int{1}
}

func (x *MipInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MipInfo) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MipInfo) GetStart() *NativeTime {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *MipInfo) GetTimeout() *NativeTime {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *MipInfo) GetActivationDelay() *NativeTime {
	if x != nil {
		return x.ActivationDelay
	}
	return nil
}

func (x *MipInfo) GetComponents() []*MipComponentEntry {
	if x != nil {
		return x.Components
	}
	return nil
}

// MipComponentEntry
type MipComponentEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind
	Kind MipComponent `protobuf:"varint,1,opt,name=kind,proto3,enum=massa.model.v1.MipComponent" json:"kind,omitempty"`
	// Version
	Version       uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MipComponentEntry) Reset() {
	*x = MipComponentEntry{}
	mi := &file_massa_model_v1_versioning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MipComponentEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MipComponentEntry) ProtoMessage() {}

func (x *MipComponentEntry) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_versioning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MipComponentEntry.ProtoReflect.Descriptor instead.
func (*MipComponentEntry) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_versioning_proto_rawDescGZIP(), []int{2}
}

func (x *MipComponentEntry) GetKind() MipComponent {
	if x != nil {
		return x.Kind
	}
	return MipComponent_MIP_COMPONENT_UNSPECIFIED
}

func (x *MipComponentEntry) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_massa_model_v1_versioning_proto protoreflect.FileDescriptor

const file_massa_model_v1_versioning_proto_rawDesc = "" +
	"\n" +
	"\x1fmassa/model/v1/versioning.proto\x12\x0emassa.model.v1\x1a\x19massa/model/v1/time.proto\"\x81\x01\n" +
	"\x0eMipStatusEntry\x122\n" +
	"\bmip_info\x18\x01 \x01(\v2\x17.massa.model.v1.MipInfoR\amipInfo\x12;\n" +
	"\bstate_id\x18\x02 \x01(\x0e2 .massa.model.v1.ComponentStateIdR\astateId\"\xa9\x02\n" +
	"\aMipInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x120\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.massa.model.v1.NativeTimeR\x05start\x124\n" +
	"\atimeout\x18\x04 \x01(\v2\x1a.massa.model.v1.NativeTimeR\atimeout\x12E\n" +
	"\x10activation_delay\x18\x05 \x01(\v2\x1a.massa.model.v1.NativeTimeR\x0factivationDelay\x12A\n" +
	"\n" +
	"components\x18\x06 \x03(\v2!.massa.model.v1.MipComponentEntryR\n" +
	"components\"_\n" +
	"\x11MipComponentEntry\x120\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1c.massa.model.v1.MipComponentR\x04kind\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion*\xf3\x01\n" +
	"\x10ComponentStateId\x12\"\n" +
	"\x1eCOMPONENT_STATE_ID_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18COMPONENT_STATE_ID_ERROR\x10\x01\x12\x1e\n" +
	"\x1aCOMPONENT_STATE_ID_DEFINED\x10\x02\x12\x1e\n" +
	"\x1aCOMPONENT_STATE_ID_STARTED\x10\x03\x12\x1f\n" +
	"\x1bCOMPONENT_STATE_ID_LOCKEDIN\x10\x04\x12\x1d\n" +
	"\x19COMPONENT_STATE_ID_ACTIVE\x10\x05\x12\x1d\n" +
	"\x19COMPONENT_STATE_ID_FAILED\x10\x06*c\n" +
	"\fMipComponent\x12\x1d\n" +
	"\x19MIP_COMPONENT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MIP_COMPONENT_ADDRESS\x10\x01\x12\x19\n" +
	"\x15MIP_COMPONENT_KEYPAIR\x10\x02B\xa5\x01\n" +
	"\x12com.massa.model.v1P\x01Z9github.com/jwmdev/massa-go/client/proto/massa/model/v1;v1\xa2\x02\x06MMODEL\xaa\x02\x12Com.Massa.Model.v1\xba\x02\x06MMODEL\xca\x02\x12Com\\Massa\\Model\\V1\xea\x02\x15Com::Massa::Model::V1b\x06proto3"

var (
	file_massa_model_v1_versioning_proto_rawDescOnce sync.Once
	file_massa_model_v1_versioning_proto_rawDescData []byte
)

func file_massa_model_v1_versioning_proto_rawDescGZIP() []byte {
	file_massa_model_v1_versioning_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_versioning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_massa_model_v1_versioning_proto_rawDesc), len(file_massa_model_v1_versioning_proto_rawDesc)))
	})
	return file_massa_model_v1_versioning_proto_rawDescData
}

var file_massa_model_v1_versioning_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_massa_model_v1_versioning_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_massa_model_v1_versioning_proto_goTypes = []any{
	(ComponentStateId)(0),     // 0: massa.model.v1.ComponentStateId
	(MipComponent)(0),         // 1: massa.model.v1.MipComponent
	(*MipStatusEntry)(nil),    // 2: massa.model.v1.MipStatusEntry
	(*MipInfo)(nil),           // 3: massa.model.v1.MipInfo
	(*MipComponentEntry)(nil), // 4: massa.model.v1.MipComponentEntry
	(*NativeTime)(nil),        // 5: massa.model.v1.NativeTime
}
var file_massa_model_v1_versioning_proto_depIdxs = []int32{
	3, // 0: massa.model.v1.MipStatusEntry.mip_info:type_name -> massa.model.v1.MipInfo
	0, // 1: massa.model.v1.MipStatusEntry.state_id:type_name -> massa.model.v1.ComponentStateId
	5, // 2: massa.model.v1.MipInfo.start:type_name -> massa.model.v1.NativeTime
	5, // 3: massa.model.v1.MipInfo.timeout:type_name -> massa.model.v1.NativeTime
	5, // 4: massa.model.v1.MipInfo.activation_delay:type_name -> massa.model.v1.NativeTime
	4, // 5: massa.model.v1.MipInfo.components:type_name -> massa.model.v1.MipComponentEntry
	1, // 6: massa.model.v1.MipComponentEntry.kind:type_name -> massa.model.v1.MipComponent
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_massa_model_v1_versioning_proto_init() }
func file_massa_model_v1_versioning_proto_init() {
	if File_massa_model_v1_versioning_proto != nil {
		return
	}
	file_massa_model_v1_time_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_massa_model_v1_versioning_proto_rawDesc), len(file_massa_model_v1_versioning_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_versioning_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_versioning_proto_depIdxs,
		EnumInfos:         file_massa_model_v1_versioning_proto_enumTypes,
		MessageInfos:      file_massa_model_v1_versioning_proto_msgTypes,
	}.Build()
	File_massa_model_v1_versioning_proto = out.File
	file_massa_model_v1_versioning_proto_goTypes = nil
	file_massa_model_v1_versioning_proto_depIdxs = nil
}
