// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: massa/api/v1/private.proto

package v1

import (
	v1 "github.com/nafsilabs/massa-go/client/proto/massa/model/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddToBootstrapBlacklistRequest holds the request for AddToBootstrapBlacklist
type AddToBootstrapBlacklistRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP addresses to add to bootstrap blacklist
	Ips           []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToBootstrapBlacklistRequest) Reset() {
	*x = AddToBootstrapBlacklistRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToBootstrapBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToBootstrapBlacklistRequest) ProtoMessage() {}

func (x *AddToBootstrapBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToBootstrapBlacklistRequest.ProtoReflect.Descriptor instead.
func (*AddToBootstrapBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{0}
}

func (x *AddToBootstrapBlacklistRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

// AddToBootstrapBlacklistResponse holds the response from AddToBootstrapBlacklist
type AddToBootstrapBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToBootstrapBlacklistResponse) Reset() {
	*x = AddToBootstrapBlacklistResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToBootstrapBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToBootstrapBlacklistResponse) ProtoMessage() {}

func (x *AddToBootstrapBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToBootstrapBlacklistResponse.ProtoReflect.Descriptor instead.
func (*AddToBootstrapBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{1}
}

// AddToBootstrapWhitelistRequest holds the request for AddToBootstrapWhitelist
type AddToBootstrapWhitelistRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP addresses to add to bootstrap whitelist
	Ips           []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToBootstrapWhitelistRequest) Reset() {
	*x = AddToBootstrapWhitelistRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToBootstrapWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToBootstrapWhitelistRequest) ProtoMessage() {}

func (x *AddToBootstrapWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToBootstrapWhitelistRequest.ProtoReflect.Descriptor instead.
func (*AddToBootstrapWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{2}
}

func (x *AddToBootstrapWhitelistRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

// AddToBootstrapWhitelistResponse holds the response from AddToBootstrapWhitelist
type AddToBootstrapWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToBootstrapWhitelistResponse) Reset() {
	*x = AddToBootstrapWhitelistResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToBootstrapWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToBootstrapWhitelistResponse) ProtoMessage() {}

func (x *AddToBootstrapWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToBootstrapWhitelistResponse.ProtoReflect.Descriptor instead.
func (*AddToBootstrapWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{3}
}

// AddToPeersWhitelistRequest holds the request for AddToPeersWhitelist
type AddToPeersWhitelistRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP addresses to add to peers whitelist
	Ips           []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToPeersWhitelistRequest) Reset() {
	*x = AddToPeersWhitelistRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToPeersWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToPeersWhitelistRequest) ProtoMessage() {}

func (x *AddToPeersWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToPeersWhitelistRequest.ProtoReflect.Descriptor instead.
func (*AddToPeersWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{4}
}

func (x *AddToPeersWhitelistRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

// AddToPeersWhitelistResponse holds the response from AddToPeersWhitelist
type AddToPeersWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToPeersWhitelistResponse) Reset() {
	*x = AddToPeersWhitelistResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToPeersWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToPeersWhitelistResponse) ProtoMessage() {}

func (x *AddToPeersWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToPeersWhitelistResponse.ProtoReflect.Descriptor instead.
func (*AddToPeersWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{5}
}

// AddStakingSecretKeysRequest holds the request for AddStakingSecretKeys
type AddStakingSecretKeysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secret keys to add to wallet
	SecretKeys    []string `protobuf:"bytes,1,rep,name=secret_keys,json=secretKeys,proto3" json:"secret_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStakingSecretKeysRequest) Reset() {
	*x = AddStakingSecretKeysRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStakingSecretKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStakingSecretKeysRequest) ProtoMessage() {}

func (x *AddStakingSecretKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStakingSecretKeysRequest.ProtoReflect.Descriptor instead.
func (*AddStakingSecretKeysRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{6}
}

func (x *AddStakingSecretKeysRequest) GetSecretKeys() []string {
	if x != nil {
		return x.SecretKeys
	}
	return nil
}

// AddStakingSecretKeysResponse holds the response from AddStakingSecretKeys
type AddStakingSecretKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStakingSecretKeysResponse) Reset() {
	*x = AddStakingSecretKeysResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStakingSecretKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStakingSecretKeysResponse) ProtoMessage() {}

func (x *AddStakingSecretKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStakingSecretKeysResponse.ProtoReflect.Descriptor instead.
func (*AddStakingSecretKeysResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{7}
}

// AllowEveryoneToBootstrapRequest holds the request for AllowEveryoneToBootstrap
type AllowEveryoneToBootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowEveryoneToBootstrapRequest) Reset() {
	*x = AllowEveryoneToBootstrapRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowEveryoneToBootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowEveryoneToBootstrapRequest) ProtoMessage() {}

func (x *AllowEveryoneToBootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowEveryoneToBootstrapRequest.ProtoReflect.Descriptor instead.
func (*AllowEveryoneToBootstrapRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{8}
}

// AllowEveryoneToBootstrapResponse holds the response from AllowEveryoneToBootstrap
type AllowEveryoneToBootstrapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowEveryoneToBootstrapResponse) Reset() {
	*x = AllowEveryoneToBootstrapResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowEveryoneToBootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowEveryoneToBootstrapResponse) ProtoMessage() {}

func (x *AllowEveryoneToBootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowEveryoneToBootstrapResponse.ProtoReflect.Descriptor instead.
func (*AllowEveryoneToBootstrapResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{9}
}

// GetBootstrapBlacklistRequest holds the request for GetBootstrapBlacklist
type GetBootstrapBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBootstrapBlacklistRequest) Reset() {
	*x = GetBootstrapBlacklistRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootstrapBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootstrapBlacklistRequest) ProtoMessage() {}

func (x *GetBootstrapBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootstrapBlacklistRequest.ProtoReflect.Descriptor instead.
func (*GetBootstrapBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{10}
}

// GetBootstrapBlacklistResponse holds the response from GetBootstrapBlacklist
type GetBootstrapBlacklistResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bootstrap blacklisted IP addresses
	Ips           []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBootstrapBlacklistResponse) Reset() {
	*x = GetBootstrapBlacklistResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootstrapBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootstrapBlacklistResponse) ProtoMessage() {}

func (x *GetBootstrapBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootstrapBlacklistResponse.ProtoReflect.Descriptor instead.
func (*GetBootstrapBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{11}
}

func (x *GetBootstrapBlacklistResponse) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

// GetBootstrapWhitelistRequest holds the request for GetBootstrapWhitelist
type GetBootstrapWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBootstrapWhitelistRequest) Reset() {
	*x = GetBootstrapWhitelistRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootstrapWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootstrapWhitelistRequest) ProtoMessage() {}

func (x *GetBootstrapWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootstrapWhitelistRequest.ProtoReflect.Descriptor instead.
func (*GetBootstrapWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{12}
}

// GetBootstrapWhitelistResponse holds the response from GetBootstrapWhitelist
type GetBootstrapWhitelistResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bootstrap whitelisted IP addresses
	Ips           []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBootstrapWhitelistResponse) Reset() {
	*x = GetBootstrapWhitelistResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootstrapWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootstrapWhitelistResponse) ProtoMessage() {}

func (x *GetBootstrapWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootstrapWhitelistResponse.ProtoReflect.Descriptor instead.
func (*GetBootstrapWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{13}
}

func (x *GetBootstrapWhitelistResponse) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

// GetMipStatusRequest holds request for GetMipStatus
type GetMipStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMipStatusRequest) Reset() {
	*x = GetMipStatusRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMipStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMipStatusRequest) ProtoMessage() {}

func (x *GetMipStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMipStatusRequest.ProtoReflect.Descriptor instead.
func (*GetMipStatusRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{14}
}

// GetMipStatusResponse holds response from GetMipStatus
type GetMipStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (MipInfo - status id) entries
	MipstatusEntries []*v1.MipStatusEntry `protobuf:"bytes,1,rep,name=mipstatus_entries,json=mipstatusEntries,proto3" json:"mipstatus_entries,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetMipStatusResponse) Reset() {
	*x = GetMipStatusResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMipStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMipStatusResponse) ProtoMessage() {}

func (x *GetMipStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMipStatusResponse.ProtoReflect.Descriptor instead.
func (*GetMipStatusResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{15}
}

func (x *GetMipStatusResponse) GetMipstatusEntries() []*v1.MipStatusEntry {
	if x != nil {
		return x.MipstatusEntries
	}
	return nil
}

// GetNodeStatusRequest holds the request for GetNodeStatus
type GetNodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeStatusRequest) Reset() {
	*x = GetNodeStatusRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeStatusRequest) ProtoMessage() {}

func (x *GetNodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{16}
}

// GetNodeStatusResponse holds the response from GetNodeStatus
type GetNodeStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node status
	Status        *v1.NodeStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeStatusResponse) Reset() {
	*x = GetNodeStatusResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeStatusResponse) ProtoMessage() {}

func (x *GetNodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeStatusResponse.ProtoReflect.Descriptor instead.
func (*GetNodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{17}
}

func (x *GetNodeStatusResponse) GetStatus() *v1.NodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// GetPeersWhitelistRequest holds the request for GetPeersWhitelist
type GetPeersWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersWhitelistRequest) Reset() {
	*x = GetPeersWhitelistRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersWhitelistRequest) ProtoMessage() {}

func (x *GetPeersWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersWhitelistRequest.ProtoReflect.Descriptor instead.
func (*GetPeersWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{18}
}

// GetPeersWhitelistResponse holds the response from GetPeersWhitelist
type GetPeersWhitelistResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whitelisted IP addresses
	Ips           []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersWhitelistResponse) Reset() {
	*x = GetPeersWhitelistResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersWhitelistResponse) ProtoMessage() {}

func (x *GetPeersWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersWhitelistResponse.ProtoReflect.Descriptor instead.
func (*GetPeersWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{19}
}

func (x *GetPeersWhitelistResponse) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

// BanNodesByIdsRequest holds the request for BanNodesByIds
type BanNodesByIdsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node ids to ban
	NodeIds       []string `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanNodesByIdsRequest) Reset() {
	*x = BanNodesByIdsRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanNodesByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanNodesByIdsRequest) ProtoMessage() {}

func (x *BanNodesByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanNodesByIdsRequest.ProtoReflect.Descriptor instead.
func (*BanNodesByIdsRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{20}
}

func (x *BanNodesByIdsRequest) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

// BanNodesByIdsResponse holds the response from BanNodesByIds
type BanNodesByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanNodesByIdsResponse) Reset() {
	*x = BanNodesByIdsResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanNodesByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanNodesByIdsResponse) ProtoMessage() {}

func (x *BanNodesByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanNodesByIdsResponse.ProtoReflect.Descriptor instead.
func (*BanNodesByIdsResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{21}
}

// BanNodesByIpsRequest holds the request for BanNodesByIps
type BanNodesByIpsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node IP addresses to ban
	Ips           []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanNodesByIpsRequest) Reset() {
	*x = BanNodesByIpsRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanNodesByIpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanNodesByIpsRequest) ProtoMessage() {}

func (x *BanNodesByIpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanNodesByIpsRequest.ProtoReflect.Descriptor instead.
func (*BanNodesByIpsRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{22}
}

func (x *BanNodesByIpsRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

// BanNodesByIpsResponse holds the response from BanNodesByIps
type BanNodesByIpsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanNodesByIpsResponse) Reset() {
	*x = BanNodesByIpsResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanNodesByIpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanNodesByIpsResponse) ProtoMessage() {}

func (x *BanNodesByIpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanNodesByIpsResponse.ProtoReflect.Descriptor instead.
func (*BanNodesByIpsResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{23}
}

// RemoveFromBootstrapBlacklistRequest holds the request for RemoveFromBootstrapBlacklist
type RemoveFromBootstrapBlacklistRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP addresses to remove from bootstrap blacklist
	Ips           []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromBootstrapBlacklistRequest) Reset() {
	*x = RemoveFromBootstrapBlacklistRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromBootstrapBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromBootstrapBlacklistRequest) ProtoMessage() {}

func (x *RemoveFromBootstrapBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromBootstrapBlacklistRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromBootstrapBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveFromBootstrapBlacklistRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

// RemoveFromBootstrapBlacklistResponse holds the response from RemoveFromBootstrapBlacklist
type RemoveFromBootstrapBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromBootstrapBlacklistResponse) Reset() {
	*x = RemoveFromBootstrapBlacklistResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromBootstrapBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromBootstrapBlacklistResponse) ProtoMessage() {}

func (x *RemoveFromBootstrapBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromBootstrapBlacklistResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromBootstrapBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{25}
}

// RemoveFromBootstrapWhitelistRequest holds the request for RemoveFromBootstrapWhitelist
type RemoveFromBootstrapWhitelistRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP addresses to remove from bootstrap whitelist
	Ips           []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromBootstrapWhitelistRequest) Reset() {
	*x = RemoveFromBootstrapWhitelistRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromBootstrapWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromBootstrapWhitelistRequest) ProtoMessage() {}

func (x *RemoveFromBootstrapWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromBootstrapWhitelistRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromBootstrapWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{26}
}

func (x *RemoveFromBootstrapWhitelistRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

// RemoveFromBootstrapWhitelistResponse holds the response from RemoveFromBootstrapWhitelist
type RemoveFromBootstrapWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromBootstrapWhitelistResponse) Reset() {
	*x = RemoveFromBootstrapWhitelistResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromBootstrapWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromBootstrapWhitelistResponse) ProtoMessage() {}

func (x *RemoveFromBootstrapWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromBootstrapWhitelistResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromBootstrapWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{27}
}

// RemoveFromPeersWhitelistRequest holds the request for RemoveFromPeersWhitelist
type RemoveFromPeersWhitelistRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP addresses to remove from peers whitelist
	Ips           []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromPeersWhitelistRequest) Reset() {
	*x = RemoveFromPeersWhitelistRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromPeersWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromPeersWhitelistRequest) ProtoMessage() {}

func (x *RemoveFromPeersWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromPeersWhitelistRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromPeersWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{28}
}

func (x *RemoveFromPeersWhitelistRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

// RemoveFromPeersWhitelistResponse holds the response from RemoveFromPeersWhitelist
type RemoveFromPeersWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromPeersWhitelistResponse) Reset() {
	*x = RemoveFromPeersWhitelistResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromPeersWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromPeersWhitelistResponse) ProtoMessage() {}

func (x *RemoveFromPeersWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromPeersWhitelistResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromPeersWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{29}
}

// RemoveStakingAddressesRequest holds the request for RemoveStakingAddresses
type RemoveStakingAddressesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Addresses to remove from staking
	Addresses     []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStakingAddressesRequest) Reset() {
	*x = RemoveStakingAddressesRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStakingAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStakingAddressesRequest) ProtoMessage() {}

func (x *RemoveStakingAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStakingAddressesRequest.ProtoReflect.Descriptor instead.
func (*RemoveStakingAddressesRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{30}
}

func (x *RemoveStakingAddressesRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// RemoveStakingAddressesResponse holds the response from RemoveStakingAddresses
type RemoveStakingAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStakingAddressesResponse) Reset() {
	*x = RemoveStakingAddressesResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStakingAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStakingAddressesResponse) ProtoMessage() {}

func (x *RemoveStakingAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStakingAddressesResponse.ProtoReflect.Descriptor instead.
func (*RemoveStakingAddressesResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{31}
}

// SignMessagesRequest holds the request for SignMessages
type SignMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Messages to sign in bytes
	Messages      [][]byte `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignMessagesRequest) Reset() {
	*x = SignMessagesRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessagesRequest) ProtoMessage() {}

func (x *SignMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessagesRequest.ProtoReflect.Descriptor instead.
func (*SignMessagesRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{32}
}

func (x *SignMessagesRequest) GetMessages() [][]byte {
	if x != nil {
		return x.Messages
	}
	return nil
}

// SignMessagesResponse holds the response from SignMessages
type SignMessagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public key that signed the message
	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Signatures
	Signatures    []string `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignMessagesResponse) Reset() {
	*x = SignMessagesResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessagesResponse) ProtoMessage() {}

func (x *SignMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessagesResponse.ProtoReflect.Descriptor instead.
func (*SignMessagesResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{33}
}

func (x *SignMessagesResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SignMessagesResponse) GetSignatures() []string {
	if x != nil {
		return x.Signatures
	}
	return nil
}

// ShutdownGracefullyRequest holds the request for ShutdownGracefully
type ShutdownGracefullyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownGracefullyRequest) Reset() {
	*x = ShutdownGracefullyRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownGracefullyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownGracefullyRequest) ProtoMessage() {}

func (x *ShutdownGracefullyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownGracefullyRequest.ProtoReflect.Descriptor instead.
func (*ShutdownGracefullyRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{34}
}

// ShutdownGracefullyResponse holds the response from ShutdownGracefully
type ShutdownGracefullyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownGracefullyResponse) Reset() {
	*x = ShutdownGracefullyResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownGracefullyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownGracefullyResponse) ProtoMessage() {}

func (x *ShutdownGracefullyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownGracefullyResponse.ProtoReflect.Descriptor instead.
func (*ShutdownGracefullyResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{35}
}

// UnbanNodesByIdsRequest holds the request for UnbanNodesByIds
type UnbanNodesByIdsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node ids to unban
	NodeIds       []string `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanNodesByIdsRequest) Reset() {
	*x = UnbanNodesByIdsRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanNodesByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanNodesByIdsRequest) ProtoMessage() {}

func (x *UnbanNodesByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanNodesByIdsRequest.ProtoReflect.Descriptor instead.
func (*UnbanNodesByIdsRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{36}
}

func (x *UnbanNodesByIdsRequest) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

// UnbanNodesByIdsResponse holds the response from UnbanNodesByIds
type UnbanNodesByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanNodesByIdsResponse) Reset() {
	*x = UnbanNodesByIdsResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanNodesByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanNodesByIdsResponse) ProtoMessage() {}

func (x *UnbanNodesByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanNodesByIdsResponse.ProtoReflect.Descriptor instead.
func (*UnbanNodesByIdsResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{37}
}

// UnbanNodesByIpsRequest holds the request for UnbanNodesByIps
type UnbanNodesByIpsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Nodes IP addresses to unban
	Ips           []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanNodesByIpsRequest) Reset() {
	*x = UnbanNodesByIpsRequest{}
	mi := &file_massa_api_v1_private_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanNodesByIpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanNodesByIpsRequest) ProtoMessage() {}

func (x *UnbanNodesByIpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanNodesByIpsRequest.ProtoReflect.Descriptor instead.
func (*UnbanNodesByIpsRequest) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{38}
}

func (x *UnbanNodesByIpsRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

// UnbanNodesByIpsResponse holds the response from UnbanNodesByIps
type UnbanNodesByIpsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanNodesByIpsResponse) Reset() {
	*x = UnbanNodesByIpsResponse{}
	mi := &file_massa_api_v1_private_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanNodesByIpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanNodesByIpsResponse) ProtoMessage() {}

func (x *UnbanNodesByIpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_massa_api_v1_private_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanNodesByIpsResponse.ProtoReflect.Descriptor instead.
func (*UnbanNodesByIpsResponse) Descriptor() ([]byte, []int) {
	return file_massa_api_v1_private_proto_rawDescGZIP(), []int{39}
}

var File_massa_api_v1_private_proto protoreflect.FileDescriptor

const file_massa_api_v1_private_proto_rawDesc = "" +
	"\n" +
	"\x1amassa/api/v1/private.proto\x12\fmassa.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19massa/model/v1/node.proto\x1a\x1fmassa/model/v1/versioning.proto\"2\n" +
	"\x1eAddToBootstrapBlacklistRequest\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\"!\n" +
	"\x1fAddToBootstrapBlacklistResponse\"2\n" +
	"\x1eAddToBootstrapWhitelistRequest\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\"!\n" +
	"\x1fAddToBootstrapWhitelistResponse\".\n" +
	"\x1aAddToPeersWhitelistRequest\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\"\x1d\n" +
	"\x1bAddToPeersWhitelistResponse\">\n" +
	"\x1bAddStakingSecretKeysRequest\x12\x1f\n" +
	"\vsecret_keys\x18\x01 \x03(\tR\n" +
	"secretKeys\"\x1e\n" +
	"\x1cAddStakingSecretKeysResponse\"!\n" +
	"\x1fAllowEveryoneToBootstrapRequest\"\"\n" +
	" AllowEveryoneToBootstrapResponse\"\x1e\n" +
	"\x1cGetBootstrapBlacklistRequest\"1\n" +
	"\x1dGetBootstrapBlacklistResponse\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\"\x1e\n" +
	"\x1cGetBootstrapWhitelistRequest\"1\n" +
	"\x1dGetBootstrapWhitelistResponse\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\"\x15\n" +
	"\x13GetMipStatusRequest\"c\n" +
	"\x14GetMipStatusResponse\x12K\n" +
	"\x11mipstatus_entries\x18\x01 \x03(\v2\x1e.massa.model.v1.MipStatusEntryR\x10mipstatusEntries\"\x16\n" +
	"\x14GetNodeStatusRequest\"K\n" +
	"\x15GetNodeStatusResponse\x122\n" +
	"\x06status\x18\x01 \x01(\v2\x1a.massa.model.v1.NodeStatusR\x06status\"\x1a\n" +
	"\x18GetPeersWhitelistRequest\"-\n" +
	"\x19GetPeersWhitelistResponse\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\"1\n" +
	"\x14BanNodesByIdsRequest\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\tR\anodeIds\"\x17\n" +
	"\x15BanNodesByIdsResponse\"(\n" +
	"\x14BanNodesByIpsRequest\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\"\x17\n" +
	"\x15BanNodesByIpsResponse\"7\n" +
	"#RemoveFromBootstrapBlacklistRequest\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\"&\n" +
	"$RemoveFromBootstrapBlacklistResponse\"7\n" +
	"#RemoveFromBootstrapWhitelistRequest\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\"&\n" +
	"$RemoveFromBootstrapWhitelistResponse\"3\n" +
	"\x1fRemoveFromPeersWhitelistRequest\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\"\"\n" +
	" RemoveFromPeersWhitelistResponse\"=\n" +
	"\x1dRemoveStakingAddressesRequest\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\" \n" +
	"\x1eRemoveStakingAddressesResponse\"1\n" +
	"\x13SignMessagesRequest\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\fR\bmessages\"U\n" +
	"\x14SignMessagesResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1e\n" +
	"\n" +
	"signatures\x18\x03 \x03(\tR\n" +
	"signatures\"\x1b\n" +
	"\x19ShutdownGracefullyRequest\"\x1c\n" +
	"\x1aShutdownGracefullyResponse\"3\n" +
	"\x16UnbanNodesByIdsRequest\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\tR\anodeIds\"\x19\n" +
	"\x17UnbanNodesByIdsResponse\"*\n" +
	"\x16UnbanNodesByIpsRequest\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\"\x19\n" +
	"\x17UnbanNodesByIpsResponse2\x93\x17\n" +
	"\x0ePrivateService\x12\xa0\x01\n" +
	"\x17AddToBootstrapBlacklist\x12,.massa.api.v1.AddToBootstrapBlacklistRequest\x1a-.massa.api.v1.AddToBootstrapBlacklistResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/add_to_boostrap_blacklist\x12\xa0\x01\n" +
	"\x17AddToBootstrapWhitelist\x12,.massa.api.v1.AddToBootstrapWhitelistRequest\x1a-.massa.api.v1.AddToBootstrapWhitelistResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/add_to_boostrap_whitelist\x12\x91\x01\n" +
	"\x13AddToPeersWhitelist\x12(.massa.api.v1.AddToPeersWhitelistRequest\x1a).massa.api.v1.AddToPeersWhitelistResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/add_to_peers_whitelist\x12\x95\x01\n" +
	"\x14AddStakingSecretKeys\x12).massa.api.v1.AddStakingSecretKeysRequest\x1a*.massa.api.v1.AddStakingSecretKeysResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/add_staking_secret_keys\x12\xa5\x01\n" +
	"\x18AllowEveryoneToBootstrap\x12-.massa.api.v1.AllowEveryoneToBootstrapRequest\x1a..massa.api.v1.AllowEveryoneToBootstrapResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/allow_everyone_to_bootstrap\x12\x98\x01\n" +
	"\x15GetBootstrapBlacklist\x12*.massa.api.v1.GetBootstrapBlacklistRequest\x1a+.massa.api.v1.GetBootstrapBlacklistResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/get_bootstrap_blacklist\x12\x98\x01\n" +
	"\x15GetBootstrapWhitelist\x12*.massa.api.v1.GetBootstrapWhitelistRequest\x1a+.massa.api.v1.GetBootstrapWhitelistResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/get_bootstrap_whitelist\x12t\n" +
	"\fGetMipStatus\x12!.massa.api.v1.GetMipStatusRequest\x1a\".massa.api.v1.GetMipStatusResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/get_mip_status\x12x\n" +
	"\rGetNodeStatus\x12\".massa.api.v1.GetNodeStatusRequest\x1a#.massa.api.v1.GetNodeStatusResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/get_node_status\x12\x88\x01\n" +
	"\x11GetPeersWhitelist\x12&.massa.api.v1.GetPeersWhitelistRequest\x1a'.massa.api.v1.GetPeersWhitelistResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/get_peers_whitelist\x12y\n" +
	"\rBanNodesByIds\x12\".massa.api.v1.BanNodesByIdsRequest\x1a#.massa.api.v1.BanNodesByIdsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/ban_nodes_by_ids\x12y\n" +
	"\rBanNodesByIps\x12\".massa.api.v1.BanNodesByIpsRequest\x1a#.massa.api.v1.BanNodesByIpsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/ban_nodes_by_ips\x12\xb5\x01\n" +
	"\x1cRemoveFromBootstrapBlacklist\x121.massa.api.v1.RemoveFromBootstrapBlacklistRequest\x1a2.massa.api.v1.RemoveFromBootstrapBlacklistResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/remove_from_bootstrap_blacklist\x12\xb5\x01\n" +
	"\x1cRemoveFromBootstrapWhitelist\x121.massa.api.v1.RemoveFromBootstrapWhitelistRequest\x1a2.massa.api.v1.RemoveFromBootstrapWhitelistResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/remove_from_bootstrap_whitelist\x12\xa5\x01\n" +
	"\x18RemoveFromPeersWhitelist\x12-.massa.api.v1.RemoveFromPeersWhitelistRequest\x1a..massa.api.v1.RemoveFromPeersWhitelistResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/remove_from_peers_whitelist\x12\x9c\x01\n" +
	"\x16RemoveStakingAddresses\x12+.massa.api.v1.RemoveStakingAddressesRequest\x1a,.massa.api.v1.RemoveStakingAddressesResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/remove_staking_addresses\x12s\n" +
	"\fSignMessages\x12!.massa.api.v1.SignMessagesRequest\x1a\".massa.api.v1.SignMessagesResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/sign_messages\x12\x8b\x01\n" +
	"\x12ShutdownGracefully\x12'.massa.api.v1.ShutdownGracefullyRequest\x1a(.massa.api.v1.ShutdownGracefullyResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/shutdown_gracefully\x12\x81\x01\n" +
	"\x0fUnbanNodesByIds\x12$.massa.api.v1.UnbanNodesByIdsRequest\x1a%.massa.api.v1.UnbanNodesByIdsResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/unban_nodes_by_ids\x12\x81\x01\n" +
	"\x0fUnbanNodesByIps\x12$.massa.api.v1.UnbanNodesByIpsRequest\x1a%.massa.api.v1.UnbanNodesByIpsResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/unban_nodes_by_ipsB\x9a\x01\n" +
	"\x10com.massa.api.v1P\x01Z:github.com/nafsilabs/massa-go/client/proto/massa/api/v1;v1\xa2\x02\x04MAPI\xaa\x02\x10Com.Massa.Api.v1\xba\x02\x04MAPI\xca\x02\x10Com\\Massa\\Api\\V1\xea\x02\x13Com::Massa::Api::V1b\x06proto3"

var (
	file_massa_api_v1_private_proto_rawDescOnce sync.Once
	file_massa_api_v1_private_proto_rawDescData []byte
)

func file_massa_api_v1_private_proto_rawDescGZIP() []byte {
	file_massa_api_v1_private_proto_rawDescOnce.Do(func() {
		file_massa_api_v1_private_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_massa_api_v1_private_proto_rawDesc), len(file_massa_api_v1_private_proto_rawDesc)))
	})
	return file_massa_api_v1_private_proto_rawDescData
}

var file_massa_api_v1_private_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_massa_api_v1_private_proto_goTypes = []any{
	(*AddToBootstrapBlacklistRequest)(nil),       // 0: massa.api.v1.AddToBootstrapBlacklistRequest
	(*AddToBootstrapBlacklistResponse)(nil),      // 1: massa.api.v1.AddToBootstrapBlacklistResponse
	(*AddToBootstrapWhitelistRequest)(nil),       // 2: massa.api.v1.AddToBootstrapWhitelistRequest
	(*AddToBootstrapWhitelistResponse)(nil),      // 3: massa.api.v1.AddToBootstrapWhitelistResponse
	(*AddToPeersWhitelistRequest)(nil),           // 4: massa.api.v1.AddToPeersWhitelistRequest
	(*AddToPeersWhitelistResponse)(nil),          // 5: massa.api.v1.AddToPeersWhitelistResponse
	(*AddStakingSecretKeysRequest)(nil),          // 6: massa.api.v1.AddStakingSecretKeysRequest
	(*AddStakingSecretKeysResponse)(nil),         // 7: massa.api.v1.AddStakingSecretKeysResponse
	(*AllowEveryoneToBootstrapRequest)(nil),      // 8: massa.api.v1.AllowEveryoneToBootstrapRequest
	(*AllowEveryoneToBootstrapResponse)(nil),     // 9: massa.api.v1.AllowEveryoneToBootstrapResponse
	(*GetBootstrapBlacklistRequest)(nil),         // 10: massa.api.v1.GetBootstrapBlacklistRequest
	(*GetBootstrapBlacklistResponse)(nil),        // 11: massa.api.v1.GetBootstrapBlacklistResponse
	(*GetBootstrapWhitelistRequest)(nil),         // 12: massa.api.v1.GetBootstrapWhitelistRequest
	(*GetBootstrapWhitelistResponse)(nil),        // 13: massa.api.v1.GetBootstrapWhitelistResponse
	(*GetMipStatusRequest)(nil),                  // 14: massa.api.v1.GetMipStatusRequest
	(*GetMipStatusResponse)(nil),                 // 15: massa.api.v1.GetMipStatusResponse
	(*GetNodeStatusRequest)(nil),                 // 16: massa.api.v1.GetNodeStatusRequest
	(*GetNodeStatusResponse)(nil),                // 17: massa.api.v1.GetNodeStatusResponse
	(*GetPeersWhitelistRequest)(nil),             // 18: massa.api.v1.GetPeersWhitelistRequest
	(*GetPeersWhitelistResponse)(nil),            // 19: massa.api.v1.GetPeersWhitelistResponse
	(*BanNodesByIdsRequest)(nil),                 // 20: massa.api.v1.BanNodesByIdsRequest
	(*BanNodesByIdsResponse)(nil),                // 21: massa.api.v1.BanNodesByIdsResponse
	(*BanNodesByIpsRequest)(nil),                 // 22: massa.api.v1.BanNodesByIpsRequest
	(*BanNodesByIpsResponse)(nil),                // 23: massa.api.v1.BanNodesByIpsResponse
	(*RemoveFromBootstrapBlacklistRequest)(nil),  // 24: massa.api.v1.RemoveFromBootstrapBlacklistRequest
	(*RemoveFromBootstrapBlacklistResponse)(nil), // 25: massa.api.v1.RemoveFromBootstrapBlacklistResponse
	(*RemoveFromBootstrapWhitelistRequest)(nil),  // 26: massa.api.v1.RemoveFromBootstrapWhitelistRequest
	(*RemoveFromBootstrapWhitelistResponse)(nil), // 27: massa.api.v1.RemoveFromBootstrapWhitelistResponse
	(*RemoveFromPeersWhitelistRequest)(nil),      // 28: massa.api.v1.RemoveFromPeersWhitelistRequest
	(*RemoveFromPeersWhitelistResponse)(nil),     // 29: massa.api.v1.RemoveFromPeersWhitelistResponse
	(*RemoveStakingAddressesRequest)(nil),        // 30: massa.api.v1.RemoveStakingAddressesRequest
	(*RemoveStakingAddressesResponse)(nil),       // 31: massa.api.v1.RemoveStakingAddressesResponse
	(*SignMessagesRequest)(nil),                  // 32: massa.api.v1.SignMessagesRequest
	(*SignMessagesResponse)(nil),                 // 33: massa.api.v1.SignMessagesResponse
	(*ShutdownGracefullyRequest)(nil),            // 34: massa.api.v1.ShutdownGracefullyRequest
	(*ShutdownGracefullyResponse)(nil),           // 35: massa.api.v1.ShutdownGracefullyResponse
	(*UnbanNodesByIdsRequest)(nil),               // 36: massa.api.v1.UnbanNodesByIdsRequest
	(*UnbanNodesByIdsResponse)(nil),              // 37: massa.api.v1.UnbanNodesByIdsResponse
	(*UnbanNodesByIpsRequest)(nil),               // 38: massa.api.v1.UnbanNodesByIpsRequest
	(*UnbanNodesByIpsResponse)(nil),              // 39: massa.api.v1.UnbanNodesByIpsResponse
	(*v1.MipStatusEntry)(nil),                    // 40: massa.model.v1.MipStatusEntry
	(*v1.NodeStatus)(nil),                        // 41: massa.model.v1.NodeStatus
}
var file_massa_api_v1_private_proto_depIdxs = []int32{
	40, // 0: massa.api.v1.GetMipStatusResponse.mipstatus_entries:type_name -> massa.model.v1.MipStatusEntry
	41, // 1: massa.api.v1.GetNodeStatusResponse.status:type_name -> massa.model.v1.NodeStatus
	0,  // 2: massa.api.v1.PrivateService.AddToBootstrapBlacklist:input_type -> massa.api.v1.AddToBootstrapBlacklistRequest
	2,  // 3: massa.api.v1.PrivateService.AddToBootstrapWhitelist:input_type -> massa.api.v1.AddToBootstrapWhitelistRequest
	4,  // 4: massa.api.v1.PrivateService.AddToPeersWhitelist:input_type -> massa.api.v1.AddToPeersWhitelistRequest
	6,  // 5: massa.api.v1.PrivateService.AddStakingSecretKeys:input_type -> massa.api.v1.AddStakingSecretKeysRequest
	8,  // 6: massa.api.v1.PrivateService.AllowEveryoneToBootstrap:input_type -> massa.api.v1.AllowEveryoneToBootstrapRequest
	10, // 7: massa.api.v1.PrivateService.GetBootstrapBlacklist:input_type -> massa.api.v1.GetBootstrapBlacklistRequest
	12, // 8: massa.api.v1.PrivateService.GetBootstrapWhitelist:input_type -> massa.api.v1.GetBootstrapWhitelistRequest
	14, // 9: massa.api.v1.PrivateService.GetMipStatus:input_type -> massa.api.v1.GetMipStatusRequest
	16, // 10: massa.api.v1.PrivateService.GetNodeStatus:input_type -> massa.api.v1.GetNodeStatusRequest
	18, // 11: massa.api.v1.PrivateService.GetPeersWhitelist:input_type -> massa.api.v1.GetPeersWhitelistRequest
	20, // 12: massa.api.v1.PrivateService.BanNodesByIds:input_type -> massa.api.v1.BanNodesByIdsRequest
	22, // 13: massa.api.v1.PrivateService.BanNodesByIps:input_type -> massa.api.v1.BanNodesByIpsRequest
	24, // 14: massa.api.v1.PrivateService.RemoveFromBootstrapBlacklist:input_type -> massa.api.v1.RemoveFromBootstrapBlacklistRequest
	26, // 15: massa.api.v1.PrivateService.RemoveFromBootstrapWhitelist:input_type -> massa.api.v1.RemoveFromBootstrapWhitelistRequest
	28, // 16: massa.api.v1.PrivateService.RemoveFromPeersWhitelist:input_type -> massa.api.v1.RemoveFromPeersWhitelistRequest
	30, // 17: massa.api.v1.PrivateService.RemoveStakingAddresses:input_type -> massa.api.v1.RemoveStakingAddressesRequest
	32, // 18: massa.api.v1.PrivateService.SignMessages:input_type -> massa.api.v1.SignMessagesRequest
	34, // 19: massa.api.v1.PrivateService.ShutdownGracefully:input_type -> massa.api.v1.ShutdownGracefullyRequest
	36, // 20: massa.api.v1.PrivateService.UnbanNodesByIds:input_type -> massa.api.v1.UnbanNodesByIdsRequest
	38, // 21: massa.api.v1.PrivateService.UnbanNodesByIps:input_type -> massa.api.v1.UnbanNodesByIpsRequest
	1,  // 22: massa.api.v1.PrivateService.AddToBootstrapBlacklist:output_type -> massa.api.v1.AddToBootstrapBlacklistResponse
	3,  // 23: massa.api.v1.PrivateService.AddToBootstrapWhitelist:output_type -> massa.api.v1.AddToBootstrapWhitelistResponse
	5,  // 24: massa.api.v1.PrivateService.AddToPeersWhitelist:output_type -> massa.api.v1.AddToPeersWhitelistResponse
	7,  // 25: massa.api.v1.PrivateService.AddStakingSecretKeys:output_type -> massa.api.v1.AddStakingSecretKeysResponse
	9,  // 26: massa.api.v1.PrivateService.AllowEveryoneToBootstrap:output_type -> massa.api.v1.AllowEveryoneToBootstrapResponse
	11, // 27: massa.api.v1.PrivateService.GetBootstrapBlacklist:output_type -> massa.api.v1.GetBootstrapBlacklistResponse
	13, // 28: massa.api.v1.PrivateService.GetBootstrapWhitelist:output_type -> massa.api.v1.GetBootstrapWhitelistResponse
	15, // 29: massa.api.v1.PrivateService.GetMipStatus:output_type -> massa.api.v1.GetMipStatusResponse
	17, // 30: massa.api.v1.PrivateService.GetNodeStatus:output_type -> massa.api.v1.GetNodeStatusResponse
	19, // 31: massa.api.v1.PrivateService.GetPeersWhitelist:output_type -> massa.api.v1.GetPeersWhitelistResponse
	21, // 32: massa.api.v1.PrivateService.BanNodesByIds:output_type -> massa.api.v1.BanNodesByIdsResponse
	23, // 33: massa.api.v1.PrivateService.BanNodesByIps:output_type -> massa.api.v1.BanNodesByIpsResponse
	25, // 34: massa.api.v1.PrivateService.RemoveFromBootstrapBlacklist:output_type -> massa.api.v1.RemoveFromBootstrapBlacklistResponse
	27, // 35: massa.api.v1.PrivateService.RemoveFromBootstrapWhitelist:output_type -> massa.api.v1.RemoveFromBootstrapWhitelistResponse
	29, // 36: massa.api.v1.PrivateService.RemoveFromPeersWhitelist:output_type -> massa.api.v1.RemoveFromPeersWhitelistResponse
	31, // 37: massa.api.v1.PrivateService.RemoveStakingAddresses:output_type -> massa.api.v1.RemoveStakingAddressesResponse
	33, // 38: massa.api.v1.PrivateService.SignMessages:output_type -> massa.api.v1.SignMessagesResponse
	35, // 39: massa.api.v1.PrivateService.ShutdownGracefully:output_type -> massa.api.v1.ShutdownGracefullyResponse
	37, // 40: massa.api.v1.PrivateService.UnbanNodesByIds:output_type -> massa.api.v1.UnbanNodesByIdsResponse
	39, // 41: massa.api.v1.PrivateService.UnbanNodesByIps:output_type -> massa.api.v1.UnbanNodesByIpsResponse
	22, // [22:42] is the sub-list for method output_type
	2,  // [2:22] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_massa_api_v1_private_proto_init() }
func file_massa_api_v1_private_proto_init() {
	if File_massa_api_v1_private_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_massa_api_v1_private_proto_rawDesc), len(file_massa_api_v1_private_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_massa_api_v1_private_proto_goTypes,
		DependencyIndexes: file_massa_api_v1_private_proto_depIdxs,
		MessageInfos:      file_massa_api_v1_private_proto_msgTypes,
	}.Build()
	File_massa_api_v1_private_proto = out.File
	file_massa_api_v1_private_proto_goTypes = nil
	file_massa_api_v1_private_proto_depIdxs = nil
}
